### ISSUE TITLE
Login refused: invalid credentials

### ISSUE THREAD

**Issue by brycethornton** [cloudamqp/amqproxy#1]
I'm trying to get this working on my local development environment. I've installed amqproxy_0.2.0-1.deb and it's running as:

```/usr/bin/amqproxy -p 5673 amqp://127.0.0.1:5672```

I've updated my app config to connect to port 5673 instead of the usual 5672 for RabbitMQ.  Everything else remains the same.  Here's the relevant config values for reference:

```
RABBITMQ_HOST="localhost"
RABBITMQ_PORT="5673"
RABBITMQ_LOGIN="guest"
RABBITMQ_PASSWORD="guest"
RABBITMQ_VHOST="/"
```

Here's our connection code using php-amqplib:

```
                $streamConnect = new AMQPStreamConnection(
                    getenv('RABBITMQ_HOST'),
                    getenv('RABBITMQ_PORT'),
                    getenv('RABBITMQ_LOGIN'),
                    getenv('RABBITMQ_PASSWORD'),
                    getenv('RABBITMQ_VHOST')
                );
```

Here's the error I'm seeing in /var/log/rabbitmq/rabbit@vagrant.log:

```
=INFO REPORT==== 3-Apr-2018::15:33:11 ===
accepting AMQP connection <0.877.0> (127.0.0.1:45566 -> 127.0.0.1:5672)

=ERROR REPORT==== 3-Apr-2018::15:33:14 ===
closing AMQP connection <0.877.0> (127.0.0.1:45566 -> 127.0.0.1:5672):
{handshake_error,starting,0,
                 {amqp_error,access_refused,
                             "PLAIN login refused: user '' - invalid credentials",
                             'connection.start_ok'}}
```

It appears that the username isn't being forwarded via the proxy. Is there anything else I should be doing to debug this?

**Comment by carlhoerberg** [comment]
Looks like it yes, strange. Will look into it soon.

**Comment by brycethornton** [comment]
We're very eager to test this out. Is there a chance we're just doing something wrong here? I'm very willing to help debug/test this out if you could give me some direction to get started. Thanks.

**Comment by carlhoerberg** [comment]
Sorry about the delay, but support for AMQPLAIN is implemented now and php-amqplib works

**Comment by brycethornton** [comment]
Thank you! I'll give it a spin now.
