### ISSUE TITLE
Consumers throughput lower after update

### ISSUE THREAD

**Issue by cloudcanyon** [cloudamqp/amqproxy#101]
Hello,
Today I updated amqproxy from 0.7.0-1 to 0.8.2-1 on Debian 10. Before the update, consumers had been working with good performance. After the update the number of messages consumed per second went very low. When I changed the consumers to connect directly to Rabbitmq, without amqproxy, the number of consumed messages per second went up again.

![indeks](https://user-images.githubusercontent.com/34484447/212127619-41eec8ab-dc2a-4290-865c-e86441e65f23.png)

The green line is the number of consumed messages per second. Between 17:10 - 17:11 I've changed the configuration from amqproxy 0.8.2-1 to direct Rabbitmq connection. Before the update (0.7.0-1 to 0.8.2-1) I had no issues.
I don't really know how to debug this case. I've used the default configuration. Previously my service was:

`/usr/bin/amqproxy -p 5673 amqp://172.31.xx.xx:5672`
And later it switched to the ini file, where I've changed only the IP, leaving the rest as default.

Has anything been changed in that scope in the recent versions?

EDITED: I have 22 consumers using 14 queues. There was no change in the producers, they still use 0.7.0-1 version on other server instances. For now I've just updated amqproxy on the server with consumers and only that activity caused the problem.

EDITED 2: I've checked the previous versions and the last version, when consumers had high throughput was 0.7.0-1.

![RabbitMQ-Management(19)](https://user-images.githubusercontent.com/34484447/212132783-c155d8c0-3961-4873-9353-6da941721483.png)

/usr/lib/systemd/system/amqproxy.service content for 0.7.0-1
```
[Unit]
Description=AMQProxy server for connection and channel pooling
Documentation=https://github.com/cloudamqp/amqproxy
Requires=network.target
After=network.target

[Service]
ExecStart=/usr/bin/amqproxy -p 5673 amqp://172.31.xx.xx:5672
Restart=on-failure
User=nobody
Group=nogroup
LimitNOFILE=8192
ProtectSystem=full

[Install]
WantedBy=multi-user.target
```

/usr/lib/systemd/system/amqproxy.service content for 0.8.0-1:
```
[Unit]
Description=AMQProxy server for connection and channel pooling
Documentation=https://github.com/cloudamqp/amqproxy
Requires=network.target
After=network.target

[Service]
ExecStart=/usr/bin/amqproxy -p 5673 amqp://172.31.xx.xx:5672
Restart=on-failure
DynamicUser=yes
LimitNOFILE=infinity

[Install]
WantedBy=multi-user.target
```

EDITED 3:
I've changed the configuration in `/usr/lib/systemd/system/amqproxy.service` for 0.8.0-1 to exactly same as for 0.7.0-1, but the problem still exists on 0.8.0-1.

**Comment by carlhoerberg** [comment]
Ok, will look into it

**Comment by carlhoerberg** [comment]
Wondering if it could be this change: https://github.com/cloudamqp/amqproxy/compare/v0.7.0...v0.8.2#diff-fea30659adacdd595d31810ba6dfb2b5f1c9885094a6b38f3d67fc6bbf5855f9L20

**Comment by cloudcanyon** [comment]
Thanks @carlhoerberg for the suggestion, it was very accurate :)

![RabbitMQ-Management(20)](https://user-images.githubusercontent.com/34484447/212316171-1823f936-0ede-46ce-b5dd-ac298e573eef.png)

I've built the amqproxy binary from sources and adding `socket.tcp_nodelay = true` to `server.cr` fixed the problem. No change in `upstream.cr`. Do you want me to do any PR with it?

**Comment by unrolled** [comment]
@carlhoerberg Can you create a release with this fix?

**Comment by carlhoerberg** [comment]
ok, done @unrolled
