### ISSUE TITLE
Performance issue with upstream.cr tcp_nodelay = false

### ISSUE THREAD

**Issue by zozs** [cloudamqp/amqproxy#109]
After an upgrade of our Kubernetes clusters (together with newer base images) we recently started seeing a 3x slowdown of our unit tests. After some debugging, we found that the majority of the time was spent clearing AMQP queues between tests.

The delay disappeared when we removed amqproxy, instead connecting directly to RabbitMQ. After this, I found  https://github.com/cloudamqp/amqproxy/issues/101. We initially used 0.8.2, but our problem exists even after an upgrade to 0.8.6.

However, I noticed that 0.8.6 only added back the TCP_NODELAY flag for the `server.cr` part (https://github.com/cloudamqp/amqproxy/commit/b6f2e53766d6b24fe154b134fd8f6b3ac2679209), but not `upstream.cr`. I manually built a version reverting both changes from (https://github.com/cloudamqp/amqproxy/commit/4e9e2c0e7297ebd798a596d0962c4910fefc60a9), i.e. also adding the TCP_NODELAY flag to `upstream.cr`.

This restored our test performance again - from 33 minutes to 11 minutes, with this being the only change in an otherwise identical setup. Is there a particular reason why only `server.cr` was reverted for 0.8.3, or could the changes in `upstream.cr` be reverted too? 

![image](https://user-images.githubusercontent.com/197840/222436451-468b26f1-b1dd-4e76-8f9c-e88d35a2401c.png) ![image](https://user-images.githubusercontent.com/197840/222443766-2170fb77-1ef6-4237-9fac-6a670c051e7f.png)

**Comment by johanrhodin** [comment]
@zozs Can you try the latest release? (`0.8.7` https://github.com/cloudamqp/amqproxy/releases/tag/v0.8.7)
