### ISSUE TITLE
Feature request: support proxy-protocol

### ISSUE THREAD

**Issue by aiceball** [cloudamqp/amqproxy#114]
## Problem

Trying to establish a connection to a RabbitMQ server that has [Proxy Protocol](https://www.rabbitmq.com/networking.html#proxy-protocol) enabled

## Environment

AMQP Client (Pika) -> HAProxy (With `send-proxy-v2` set in config) -> AMQProxy -> RabbitMQ Server (with `proxy_protocol = true` enabled)

## Symptoms

`Transport indicated EOF` - from client
`port_5673 port_5673/rmq1 1/1/4 8 -- 2/1/0/0/0 0/0` - from HAProxy logs
`amqproxy[387178]: Client disconnected: 192.168.1.76:37026: #<AMQProxy::Client::NegotiationError:Client negotiation failed>` - from amqproxy logs 
No error logs from RabbitMQ Server

**Comment by carlhoerberg** [comment]
This doesn't make sense to implement, the initial connection might come from a specific ip, but then the proxy will keep that connection open, and another client from another IP might reuse it, making the initial IP in the PROXY protocol misguided.
