### ISSUE TITLE
87 Illegal instruction (core dumped) amqproxy

### ISSUE THREAD

**Issue by armenr** [cloudamqp/amqproxy#117]
I'm having one heck of a time debugging some intermittent issues I'm seeing with AMQProxy.

I have a pod in Kubernetes that runs AMQProxy inside. Most of the time, AMQProxy works great. No issue. We've used it a bunch, run our automated QA against the servers and applications that are now using AMQProxy...most of the time, no issues! Just awesomeness!

But, I'm seeing an intermittent issue with the proxy.

We have some scripts that need to run before our PHP-FPM app starts up. Those scripts do a bunch of PHP-related things, and then, after that's done, we start php-fpm.

Sometimes, our code will throw an error when starting. Right before our code throws the error, it looks like the proxy throws a fault and crashes.

At the start of the container startup logs, I clearly see: 

```
qa/qa-monometa-59f764cd5b-p9sts[app]: s6-rc: info: service run-01-amqproxy: starting
qa/qa-monometa-59f764cd5b-p9sts[app]: s6-rc: info: service s6rc-fdholder: starting
qa/qa-monometa-59f764cd5b-p9sts[app]: s6-rc: info: service s6rc-oneshot-runner: starting
qa/qa-monometa-59f764cd5b-p9sts[app]: s6-rc: info: service run-01-amqproxy successfully started
qa/qa-monometa-59f764cd5b-p9sts[app]: s6-rc: info: service s6rc-oneshot-runner successfully started
qa/qa-monometa-59f764cd5b-p9sts[app]: s6-rc: info: service fix-attrs: starting
qa/qa-monometa-59f764cd5b-p9sts[app]: s6-rc: info: service init-01-setup-files: starting
qa/qa-monometa-59f764cd5b-p9sts[app]: s6-rc: info: service s6rc-fdholder successfully started
qa/qa-monometa-59f764cd5b-p9sts[app]: [Startup] Starting amqproxy...
qa/qa-monometa-59f764cd5b-p9sts[app]: [Startup] Setting up file and filesystem...
qa/qa-monometa-59f764cd5b-p9sts[app]: [Startup] Setting /tmp directory permissions (just to be safe)...
qa/qa-monometa-59f764cd5b-p9sts[app]: s6-rc: info: service fix-attrs successfully started
qa/qa-monometa-59f764cd5b-p9sts[app]: s6-rc: info: service legacy-cont-init: starting
qa/qa-monometa-59f764cd5b-p9sts[app]: 2023-05-17 15:10:18 +00:00: Proxy upstream: REDACTED_ENDPOINT.mq.us-west-2.amazonaws.com:5671 TLS
qa/qa-monometa-59f764cd5b-p9sts[app]: s6-rc: info: service init-01-setup-files successfully started
qa/qa-monometa-59f764cd5b-p9sts[app]: 2023-05-17 15:10:18 +00:00: Proxy listening on 127.0.0.1:5671
```

So, I know for sure that the proxy is up and listening/working.

Half a second later, I see these:

```
qa/qa-monometa-59f764cd5b-p9sts[app]: [RUN 03] Initialize META...
qa/qa-monometa-59f764cd5b-p9sts[app]: 2023-05-17 15:10:18 +00:00: Client connected: 127.0.0.1:44656
```

SO, at this point, I know for a fact that the proxy is accepting and serving connections, and everything's working.

Then, a half-second-or-so later

```
qa/qa-monometa-59f764cd5b-p9sts[app]: [2023-05-17T15:10:29.925+0000][DEBUG][InstallEvents#475] Install video event property proxy.proxies: high
qa/qa-monometa-59f764cd5b-p9sts[app]: [2023-05-17T15:10:29.926+0000][DEBUG][InstallEvents#475] Install video event property proxy.proxies: low
qa/qa-monometa-59f764cd5b-p9sts[app]: [2023-05-17T15:10:29.926+0000][DEBUG][InstallEvents#475] Install video event property proxy.proxies: audio
qa/qa-monometa-59f764cd5b-p9sts[app]: [2023-05-17T15:10:29.927+0000][DEBUG][InstallEvents#475] Install video event property proxy.forensic: high
qa/qa-monometa-59f764cd5b-p9sts[app]: [2023-05-17T15:10:29.927+0000][DEBUG][InstallEvents#475] Install video event property proxy.thumbnails: small
qa/qa-monometa-59f764cd5b-p9sts[app]: [2023-05-17T15:10:29.928+0000][DEBUG][InstallEvents#475] Install video event property proxy.thumbnails: medium
qa/qa-monometa-59f764cd5b-p9sts[app]: [2023-05-17T15:10:29.928+0000][DEBUG][InstallEvents#475] Install video event property proxy.thumbnails: high
qa/qa-monometa-59f764cd5b-p9sts[app]: 2023-05-17 15:10:29 +00:00: Client connected: 127.0.0.1:39802
qa/qa-monometa-59f764cd5b-p9sts[app]: 2023-05-17 15:10:29 +00:00: Client connected: 127.0.0.1:39812
qa/qa-monometa-59f764cd5b-p9sts[app]: 2023-05-17 15:10:29 +00:00: Client connected: 127.0.0.1:39828
qa/qa-monometa-59f764cd5b-p9sts[app]: [2023-05-17T15:10:30.055+0000][DEBUG][InstallEvents#475] Install event logic for trigger: "asperaDownloadReady"
qa/qa-monometa-59f764cd5b-p9sts[app]: ./run: line 4:    87 Illegal instruction     (core dumped) amqproxy --listen=127.0.0.1 --port=$RABBITMQ_PROXY_PORT --idle-connection-timeout=$AMQPROXY_IDLE_TIMEOUT --debug amqps://$RABBITMQ_PROXY_HOST:$RABBITMQ_PROXY_PORT
qa/qa-monometa-59f764cd5b-p9sts[app]:
qa/qa-monometa-59f764cd5b-p9sts[app]: In StreamIO.php line 171:
qa/qa-monometa-59f764cd5b-p9sts[app]:
qa/qa-monometa-59f764cd5b-p9sts[app]:   Broken pipe or closed connection
qa/qa-monometa-59f764cd5b-p9sts[app]:
qa/qa-monometa-59f764cd5b-p9sts[app]:
qa/qa-monometa-59f764cd5b-p9sts[app]: tools:install:event-manager-events
qa/qa-monometa-59f764cd5b-p9sts[app]:
qa/qa-monometa-59f764cd5b-p9sts[app]: s6-rc: warning: unable to start service init-03-init-app: command exited 1
qa/qa-monometa-59f764cd5b-p9sts[app]: [Startup] Starting amqproxy...
qa/qa-monometa-59f764cd5b-p9sts[app]: 2023-05-17 15:10:31 +00:00: Proxy upstream: SOME_AMQ_CLUSTER:5671 TLS
qa/qa-monometa-59f764cd5b-p9sts[app]: 2023-05-17 15:10:31 +00:00: Proxy listening on 127.0.0.1:5671
```

This happens intermittently. There's no trigger or condition I've been able to find or use, in order to reproduce this consistently. It just happens at random.

As you can see at the end of the last log snippet, the proxy crashes, which causes the app to crash, and then s6-overlay restarts the proxy instantly, and the proxy comes right back...but our initialization script breaks, and the app never starts.

I'm wondering two things:

1. How do you debug this? I already have `--debug` set on amqProxy
2. What does `87 Illegal instruction     (core dumped)` mean?

If it helps, this is how we run AMQProxy with s6-overlay (as an s6-rc service)

```
set -o errexit
echo "[Startup] Starting amqproxy..."
amqproxy --listen=127.0.0.1 --port=$RABBITMQ_PROXY_PORT --idle-connection-timeout=$AMQPROXY_IDLE_TIMEOUT --debug amqps://$RABBITMQ_PROXY_HOST:$RABBITMQ_PROXY_PORT
EXIT_CODE=$?
echo "AMQPROXY EXITED: ${EXIT_CODE}"

```

**Comment by carlhoerberg** [comment]
What exact CPU are you running this on?

**Comment by carlhoerberg** [comment]
Why are you compiling it yourself? Still seeing issues when running the "official" amqproxy image and/or the official deb packages? 

the EOFError is just a normal network disruption. Not related to the "Invalid instruction". 

You should analyze the coredump: `gdb <executable> <core-file>`, issue `bt` to get the backtrace.

**Comment by carlhoerberg** [comment]
The core dump is dumped on the host machine, see `/proc/sys/kernel/core_pattern` for where to. You just need to increase the core dump size limit for the container with something like: `docker run --ulimit core=-1 ...` or something along those lines with kubernetes. 

more info: https://stackoverflow.com/questions/28335614/how-to-generate-core-file-in-docker-container

The tricky thing when running in a container is that you have to give gdb the path to the binary, which is in the image, but should be possible somehow from the host machine.

**Comment by carlhoerberg** [comment]
Uprobe is "User-level dynamic tracing" probes, from perf, ebpf or similar.
Maybe it's a kernel bug, which kernel version are you using?

amqperf is not doing any tracing, it's something else that tries to trace
it.

Can you type `bt` in gdb so that we get the stacktrace?

**Comment by dentarg** [comment]
Just throwing some things out there:

@armenr which version of Kubernetes are you running? If I understand it correctly, you need at least 1.27 for eBPF support: https://github.com/awslabs/amazon-eks-ami/issues/728, https://github.com/awslabs/amazon-eks-ami/pull/1223 

Or maybe something like https://github.com/iovisor/bcc/issues/1320 is going on?

**Comment by dentarg** [comment]
Reading more about this, it seems clear that we are in the same both as Go here, from https://github.com/golang/go/issues/27077#issuecomment-415141461

> The only difference is that Go depends on its ability to unwind stacks for GC and stack growth. I assert that uretprobes would break stack unwinding in any language, and regardless of calling convention. I'm actually really curious how it interacts with C++ exception handling; I suspect uretprobes breaks it.
>
> uretprobes clobbers critical unwinding information and, as far as I can tell, doesn't provide a way to get it back. However, I would love to be proved wrong, since I know how powerful uprobes can be.

[Crystal](https://github.com/crystal-lang/crystal/blob/master/src/exception/call_stack/libunwind.cr) also does [stack unwinding](https://en.wikipedia.org/wiki/Call_stack#Unwinding), so disabling Pixie was the right call (and nice work @armenr to eventually finding that), to avoid these crashes. It is unfortunate, as everything on https://docs.px.dev/about-pixie/pixie-ebpf sounds pretty cool, but that's the situation.

I'm going to close this issue as we can't address it in this project.

**Comment by ddelnano** [comment]
Hey all, Pixie core maintainer here. Sorry to hear that these uprobes were causing amqproxy issues.

I know you mentioned that you uninstalled Pixie from your cluster, but we (the maintainers) care about addressing issues like this. I've created https://github.com/pixie-io/pixie/issues/1970 to provide a mechanism for opting applications out of uprobe instrumentation. Wanted to mention that in case anyone else runs into this issue or you are interested in trying Pixie again.
