### ISSUE TITLE
RPM support for Centos

### ISSUE THREAD

**Issue by srjwebster** [cloudamqp/amqproxy#119]
Hi all, the host for this package at packagecloud seems to suggest we can install for /el/7 systems.

I've run through the installer and can see from yum repoinfo that https://packagecloud.io/cloudamqp/amqproxy/el/7/x86_64/ is empty. Any reason for this?

**Comment by carlhoerberg** [comment]
Is CentOS still maintained? Which version are you targeting?

**Comment by srjwebster** [comment]
By place of work is still using el/7 architecture, which won't change in a hurry, and currently we're dying from connection churn in our architecture. I can solve it by batching up messages for a period and sending many at once, but I'd rather keep them on demand which the proxy would really help with

**Comment by carlhoerberg** [comment]
el/7 is ancient, latest llvm version in el/7 is 3.4.2, which crystal doesn't support, 8 or newer is required. llvm 3.4.2 was released in 19 Jun 2014. Soon 10 years ago!

**Comment by srjwebster** [comment]
Latest Kernel update last month:
https://linuxsoft.cern.ch/cern/centos/7/updates/x86_64/repoview/kernel.html

**Comment by carlhoerberg** [comment]
Ok, latest container image of centos 7 i could find was 3 years old: https://quay.io/repository/centos/centos?tab=tags&tag=latest

The docker hub repo has a heavy deprecation warning: https://hub.docker.com/_/centos

and officially it's deprecated in less than 4 months: https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/

**Comment by carlhoerberg** [comment]
> ...it's less relevant now!

which dist did you migrate to?
