### ISSUE TITLE
upstream per-vhost

### ISSUE THREAD

**Issue by spreegabe** [cloudamqp/amqproxy#121]
Are there any reasons why we couldn't or shouldn't do an upstream per vhost? It looks like the source would already support that, just have to tweak the pool creation a bit?

**Comment by dentarg** [comment]
@spreegabe isn't that what we're doing with the `{user, password, vhost}` tuple? or what do you have in mind? Maybe I'm not understanding what you want :)

**Comment by spreegabe** [comment]
Well yeah that tuple seems like it would support it, but the entrypoint doesn't support multiple upstreams, and explicitly only checks for `scheme, host and port (optional)`. I don't know enough about rabbitmq connections and tls to say with confidence if this would work, but it would be cool to say 'hey, use this global rabbitmq endpoint', and folks and applications end up on the 'dev' upstream if their vhost matches '^dev.*$' and the  prod vhost if their vhost had 'prod.*', etc.

or if we integrated it with the management api, and the proxy could dynamically create vhosts if they didn't exist, or like remap them. not sure if any of those are useful things but it would be cool, right?

**Comment by dentarg** [comment]
Thanks for elaborating. I think (the first part) is something you can do with https://github.com/bloomberg/amqpprox (note: I haven't used this project myself). Feel free to report back here if you try it.

I'm not sure if this project will go there but we can leave this issue open for now if anyone else want to express their interest.
