### ISSUE TITLE
amqproxy 0.8.11 still Points to amqproxy 0.8.8 binaries 

### ISSUE THREAD

**Issue by ashahmali3** [cloudamqp/amqproxy#122]
Although I am using the docker container based on amqproxy 0.8.11 my tools are still picking up amqproxy 0.8.8

The changelog also only goes up to 0.8.9, am not sure how to interpret this

./shard.yml still references version 0.8.8 

https://github.com/cloudamqp/amqproxy/releases/tag/v0.8.11

```
$ docker run -it --entrypoint /bin/sh cloudamqp/amqproxy:v0.8.11
/ $ ps
PID   USER     TIME  COMMAND
    1 amqpprox  0:00 /bin/sh
    7 amqpprox  0:00 ps
/ $ ls
bin    dev    etc    home   lib    media  mnt    opt    proc   root   run    sbin   srv    sys    tmp    usr    var
/ $ amqproxy -v
0.8.8
```

**Comment by dentarg** [comment]
Yes, unfortunately the version number was not updated in `shards.yml` as it should have been, but it was in https://github.com/cloudamqp/amqproxy/commit/8d840aad48d14b765e6f14646465fcc6c4d28306, so now the reporting is correct:

```
$ docker run -it --entrypoint /bin/sh cloudamqp/amqproxy:v0.8.12
/ $ amqproxy -v
```
