### ISSUE TITLE
Standard init.d file to launch amqproxy with service and not systemd

### ISSUE THREAD

**Issue by TristanPouliquen** [cloudamqp/amqproxy#125]
Hello,

Our docker images use `service` and not `systemd` to launch our background services.

Do you have an init.d file that will allow us to launch amqproxy with `service`?

Best,

**Comment by carlhoerberg** [comment]
Why do you start background services at all in docker? "Best practice" is that you have a seperate container for services, eg your DB, or in this case the proxy. Docker compose makes that process easy. In kubernetes it's common that you deploy amqproxy as a sidecar.
