### ISSUE TITLE
[Documentation] Idle connection timeout vs Heartbeat

### ISSUE THREAD

**Issue by sylfabre** [cloudamqp/amqproxy#126]
Hello

Thank you for proving this proxy!

Does this proxy keep sending heartbeat frames to the upstream server on idle connections?

Let's consider this scenario:
- Connection with a heartbeat of 120 seconds
- Proxy with an idle connection timeout of 300 seconds

The connection is idle meaning no client is using it or sending heartbeat frames.
Will the proxy keep sending heartbeat frames to keep the connection alive?

Thanks!

**Comment by baelter** [comment]
The proxy will answer heartbeats from both the client and the upstream, but does not send out any of it's own. When the idle connection timeout is reached (without receiving any heartbeats), the connection is closed.

**Comment by carlhoerberg** [comment]
We recommend disabling AMQP heartbeats and instead rely on TCP keepalive packages.
