### ISSUE TITLE
INFO log level too verbose 

### ISSUE THREAD

**Issue by s-maj** [cloudamqp/amqproxy#13]
With 10000 non-persistent connections connecting and disconnecting all the time, there is too much noise in the logs. I understand this approach is to replicate RabbitMQ logs behaviour but this tool is mainly for producers/consumers that can't handle long lived connections.

**Comment by carlhoerberg** [comment]
Closed with https://github.com/cloudamqp/amqproxy/commit/e2237cd1a2c2782318be106339dd3abb49445df0
