### ISSUE TITLE
upgrading deb package lead to replace config to default value

### ISSUE THREAD

**Issue by akhomyakov-marfatech** [cloudamqp/amqproxy#139]
**Description:**
Upon updating the application package from version 0.8.8-1 to 0.8.12-1, the application's config file was unexpectedly replaced with default values.

**Steps to Reproduce:**

Install version 0.8.8-1 of the application.
Modify the application's config file with custom values.
Update the application package to version 0.8.12-1.
Check the application's config file.
Expected Result:
The application's config file retains the custom values set by the user.

**Actual Result:**
The application's config file was overwritten with default values.

**Severity:**
High – Users might lose their customized settings which can impact their workflow or functionality of the application.

**Attachments:**
Attached screenshot showcasing the problem

**Comment by akhomyakov-marfatech** [comment]
<img width="1030" alt="Screenshot 2023-10-19 at 18 15 14" src="https://github.com/cloudamqp/amqproxy/assets/81229565/03fd7f43-89e1-4a5d-88d0-b1952c2ad282">

**Comment by carlhoerberg** [comment]
Thank you for reporting! Fixed
