### ISSUE TITLE
Alpine (3.19+) no longer has libssl1.1

### ISSUE THREAD

**Issue by Keartland** [cloudamqp/amqproxy#141]
Building the DockerFIle with `docker build -t amqproxy .` errors due to alpine latest not having libssl1.1.

Quick work around is using alpine:3.18 rather than latest.

Longer workaround would be to support libssl3 or build libssl1.1 in dockerfile.

STEPS TO REPRODUCE:
```
git clone https://github.com/cloudamqp/amqproxy.git
cd amqproxy
docker build -t amqproxy .
```

**Comment by dentarg** [comment]
For for reporting, I changed the main branch to use Alpine 3.18 for now.

**Comment by carlhoerberg** [comment]
Fixed in https://github.com/cloudamqp/amqproxy/commit/bd951024f3113b9603d49d331bf84409704f386a
