### ISSUE TITLE
1.0.0 Release?

### ISSUE THREAD

**Issue by orlandothoeny** [cloudamqp/amqproxy#145]
When we initially adopted AMQProxy, we were a bit wary. Because a `0.x` version usually indicates that there might be multiple breaking changes until a stable version drops. Due to that, we reached out to the CloudAMQP support (we run our RabbitMQ instances there) to get the assurance that this projects has their long term support.

A stable version release might help in such cases, increase confidence and adoption.

I am wondering what the roadmap regarding a first stable release looks like (if there's any)?
Are there any missing features / blockers that first need to be addressed before a 1.0.0 version can be tagged?

Would commitment to [semantic versioning](https://semver.org/) be viable for you? That would also give the users more clarity about what can be expected of releases. This could be documented in the project's README.

**Comment by carlhoerberg** [comment]
1.0.0 is released, and so is 2.0.0-rc.1 (which changes the behavior substantially, going from mapping one client connection to one upstream connection, to instead pool channels, many client connections can share a single upstream connection and the proxy will remap channels between them).
