### ISSUE TITLE
Client is not notified when connection gets blocked

### ISSUE THREAD

**Issue by 4selin** [cloudamqp/amqproxy#146]
RabbitMQ notifies clients when connection gets blocked.
https://rabbitmq-website.pages.dev/docs/connection-blocked

My app do receive such notification if it is connected directly to RabbitMQ.
But if app connected through AMQProxy no notification comes. 

AMQProxy runs in docker https://hub.docker.com/r/cloudamqp/amqproxy
version: 2.0.0-rc.1

**Comment by carlhoerberg** [comment]
Ok, will implement

**Comment by carlhoerberg** [comment]
v2.0.0-rc.2 with this fix is out, thank you for reporting
