### ISSUE TITLE
Trying to install - repo seems missing?

### ISSUE THREAD

**Issue by TheVillageGuy** [cloudamqp/amqproxy#149]
Running `curl -s https://packagecloud.io/install/repositories/cloudamqp/amqproxy/script.deb.sh | sudo bash` and then apt-get update gives me

```
Err:12 https://packagecloud.io/cloudamqp/amqproxy/debian bookworm Release
  404  Not Found [IP: 2600:1f1c:2e5:6901:7d8b:82c3:d880:13b0 443]
```
on debian bookworm

**Comment by dentarg** [comment]
It is just that [Debian 12](https://www.debian.org/releases/bookworm/) is still very new and packages haven't been built for it. I opened #150 for that.
