### ISSUE TITLE
[2.0.0-rc.1-1] Channel not restarted when is killed by server due to error

### ISSUE THREAD

**Issue by cosminardeleanu** [cloudamqp/amqproxy#151]
How to reproduce:
- have 2.0.0-rc.1-1 installed
- start a worker/consume on non existent queue.
  - worker will crash, with `Server channel error: 404, message: NOT_FOUND - no queue 'test' in vhost '/'`
- start the worker again
- no error message, the consumer "works" but actually does nothing, it just keeps the channel occupied.

I assume this might can also happen when:
- you declare a queue/exchange, with different config than the existing one.
  - this kind of declaration will usually result into a precondition_failed error, and connection/channel can no longer be reused.

Edit: Tested a bit more, and is related only to channel, not connection too. The connection is working fine, as long a new channel is created to be used (this means there must be a worker stuck on channel 1, to trigger a channel 2 to be created and used)

**Comment by carlhoerberg** [comment]
Could not reproduce unless I'm missing some detail. 

```crystal
require "amqp-client"

AMQP::Client.start("amqp://localhost") do |c|
  qname = "test#{rand}"
  loop do
    ch1 = c.channel
    ch1.basic_consume(qname, block: true) { }
  rescue
    next
  end
end
```

Sound maybe like you have a buggy client that allows you to reuse the closed/crashed channel? Which client lib are you using?

**Comment by carlhoerberg** [comment]
Ok, was able to reproduce, working on a fix

**Comment by carlhoerberg** [comment]
v2.0.0-rc.2 with this fix is out, thank you for reporting
