### ISSUE TITLE
[2.0.0-rc.2] Channel stuck, when publish to non existent exchange

### ISSUE THREAD

**Issue by cosminardeleanu** [cloudamqp/amqproxy#154]
Related to https://github.com/cloudamqp/amqproxy/issues/151

Let's have 2 scripts (think about them as cronjobs), A and B:
- start script A, publish a message to exchange "X" (which exists)
  - job finishes, message received
  - channel 1 was used
- start script B, publish a message to exchange "Z" (which does not exists)
  - no error caught, script looks like it was successful
  - channel 1 was used
- from now on, when script A will start, it will act like everything is ok, but the message never arrives the exchange

**Comment by carlhoerberg** [comment]
Thank you for reporting! Should be fixed now
