### ISSUE TITLE
[2.0.0-rc.2] Channels are not being closed

### ISSUE THREAD

**Issue by LorenzoRogai** [cloudamqp/amqproxy#156]
Hi,

With the rc2 we are noticing this behaviour. Channels counts increase continuously and then AMQP Proxy opens a new connection

<img width="1218" alt="image" src="https://github.com/cloudamqp/amqproxy/assets/1665768/b9a6c68d-68c3-452b-afb4-3629afd65bdd">

Additionally it shows only 721 TCP connections but on the RabbitMQ panel we are seeing 2-3 connections with over 2k channels each

<img width="406" alt="image" src="https://github.com/cloudamqp/amqproxy/assets/1665768/884bd036-8f77-4145-8302-7cd0c4b8d039">

**Comment by carlhoerberg** [comment]
Wasnt an issue? As you closed it?

**Comment by LorenzoRogai** [comment]
@carlhoerberg yeah. We discovered that a consumer was calling a function that was publishing messages (by instantiating the PhpAmqpLib client class). We now cached the class instance as static
