### ISSUE TITLE
Error writing to upstream (AMQProxy::Upstream::WriteError) 

### ISSUE THREAD

**Issue by vb0om** [cloudamqp/amqproxy#157]
RabbitMQ server version 3.10.7
Client: .Net application with MassTransit

Logs from AMQPROXY:
```
2024-04-19T06:38:54.457398Z  INFO amq_proxy.channel_pool[remote_address: "10.100.129.143:42960"] Adding upstream connection   │
│ 2024-04-19T06:39:08.426607886Z amqproxy-97d764967-nn546 2024-04-19T06:39:08.426461Z ERROR amq_proxy.client[remote_address: "10.100.130.213:50388"] Upstream error                     │
│ 2024-04-19T06:39:08.426695406Z amqproxy-97d764967-nn546 Error writing to upstream (AMQProxy::Upstream::WriteError)                                                                    │
│ 2024-04-19T06:39:08.427559820Z amqproxy-97d764967-nn546   from tmp/src/amqproxy/upstream.cr:176:9 in 'read_loop'                                                                      │
│ 2024-04-19T06:39:08.427581123Z amqproxy-97d764967-nn546   from tmp/src/amqproxy/client.cr:28:5 in '->'                                                                                │
│ 2024-04-19T06:39:08.427586510Z amqproxy-97d764967-nn546   from usr/share/crystal/src/fiber.cr:146:11 in 'run'                                                                         │
│ 2024-04-19T06:39:08.427591531Z amqproxy-97d764967-nn546   from ???                                                                                                                    │
│ 2024-04-19T06:39:08.427596390Z amqproxy-97d764967-nn546 Caused by: Closed stream (IO::Error)                                                                                          │
│ 2024-04-19T06:39:08.428446953Z amqproxy-97d764967-nn546   from usr/share/crystal/src/io.cr:121:5 in 'write'                                                                           │
│ 2024-04-19T06:39:08.428466414Z amqproxy-97d764967-nn546   from tmp/lib/amq-protocol/src/amq/protocol/frames.cr:18:9 in 'to_io'                                                        │
│ 2024-04-19T06:39:08.428472577Z amqproxy-97d764967-nn546   from tmp/src/amqproxy/upstream.cr:172:9 in 'read_loop'                                                                      │
│ 2024-04-19T06:39:08.428477684Z amqproxy-97d764967-nn546   from tmp/src/amqproxy/client.cr:28:5 in '->'                                                                                │
│ 2024-04-19T06:39:08.428482533Z amqproxy-97d764967-nn546   from usr/share/crystal/src/fiber.cr:146:11 in 'run'                                                                         │
│ 2024-04-19T06:39:08.428506153Z amqproxy-97d764967-nn546   from ???
```
Logs from .Net application:
```
2024-04-19T06:00:27.202478884Z stdout F fail: MassTransit[0]
2024-04-19 09:00:27.202	
2024-04-19T06:00:27.202504108Z stdout F       Declare queue faulted: name: <QUEUE_NAME>, durable
2024-04-19 09:00:27.203	
2024-04-19T06:00:27.203189309Z stdout F       RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=500, text='UPSTREAM_DISCONNECTED', classId=0, methodId=0
2024-04-19 09:00:27.203	
2024-04-19T06:00:27.203210282Z stdout F          at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
2024-04-19 09:00:27.203	
2024-04-19T06:00:27.203227608Z stdout F          at RabbitMQ.Client.Impl.ModelBase.QueueDeclare(String queue, Boolean passive, Boolean durable, Boolean exclusive, Boolean autoDelete, IDictionary`2 arguments)
2024-04-19 09:00:27.203	
2024-04-19T06:00:27.203233331Z stdout F          at RabbitMQ.Client.Impl.ModelBase.QueueDeclare(String queue, Boolean durable, Boolean exclusive, Boolean autoDelete, IDictionary`2 arguments)
2024-04-19 09:00:27.203	
2024-04-19T06:00:27.20327514Z stdout F          at MassTransit.Util.ChannelExecutor.SynchronousFuture`1.Run() in /_/src/MassTransit/Util/ChannelExecutor.cs:line 280
2024-04-19 09:00:27.203	
2024-04-19T06:00:27.203280973Z stdout F       --- End of stack trace from previous location ---
```
Maybe anyone has some ideas?

**Comment by dentarg** [comment]
Which version of amqproxy are you running?

**Comment by dentarg** [comment]
When does this happen for you?

**Comment by vb0om** [comment]
> Which version of amqproxy are you running?

The version of amqproxy is "v2.0.0-rc.2"

**Comment by vb0om** [comment]
> When does this happen for you?

All of this from the logs of application. Since that moment we have canceled implementation of amqproxy ...
But I still want to use it to handle our TCP connections, because from the logs of rabbitmq I found that our apps recreated TCP connections, so it overloads rabbitmq and I want to change this flow.

**Comment by vb0om** [comment]
> adding on to this issue, over at Mbin (PHP Symfony 7 application) (https://github.com/MbinOrg/mbin) we recommend instance/server admins deploy AMQProxy so as to not overload RabbitMQ (3.13.1) during periods of high federation activity, but we started seeing the same sort of behavior with the v2.0.0-rc.2 release of AMQProxy:
> 
> ```
> Apr  8 04:06:55 amqproxy[4647]: Caused by: Closed stream (IO::Error)
> Apr  8 04:06:55 amqproxy[4647]:   from usr/share/crystal/src/io/buffered.cr:130 in 'write'
> Apr  8 04:06:55 amqproxy[4647]:   from tmp/amqproxy/lib/amq-protocol/src/amq/protocol/frames.cr:18:9 in 'to_io'
> Apr  8 04:06:55 amqproxy[4647]:   from tmp/amqproxy/src/amqproxy/upstream.cr:172:9 in 'send'
> Apr  8 04:06:55 amqproxy[4647]:   from tmp/amqproxy/src/amqproxy/upstream.cr:60:11 in 'unassign'
> Apr  8 04:06:55 amqproxy[4647]:   from tmp/amqproxy/src/amqproxy/client.cr:48:13 in 'read_loop'
> Apr  8 04:06:55 amqproxy[4647]:   from tmp/amqproxy/src/amqproxy/server.cr:74:7 in '->'
> Apr  8 04:06:55 amqproxy[4647]:   from usr/share/crystal/src/fiber.cr:146:11 in 'run'
> Apr  8 04:06:55 amqproxy[4647]:   from ???
> Apr  8 04:06:56 amqproxy[4647]: amq_proxy.client[remote_address: "127.0.0.1:54186"] Upstream error
> Apr  8 04:06:56 amqproxy[4647]: Error writing to upstream (AMQProxy::Upstream::WriteError)
> Apr  8 04:06:56 amqproxy[4647]:   from tmp/amqproxy/src/amqproxy/upstream.cr:176:9 in 'read_loop'
> Apr  8 04:06:56 amqproxy[4647]:   from tmp/amqproxy/src/amqproxy/server.cr:74:7 in '->'
> Apr  8 04:06:56 amqproxy[4647]:   from usr/share/crystal/src/fiber.cr:146:11 in 'run'
> Apr  8 04:06:56 amqproxy[4647]:   from ???
> Apr  8 04:06:56 amqproxy[4647]: Caused by: Closed stream (IO::Error)
> Apr  8 04:06:56 amqproxy[4647]:   from usr/share/crystal/src/io/buffered.cr:130 in 'write'
> Apr  8 04:06:56 amqproxy[4647]:   from tmp/amqproxy/lib/amq-protocol/src/amq/protocol/frames.cr:18:9 in 'to_io'
> Apr  8 04:06:56 amqproxy[4647]:   from tmp/amqproxy/src/amqproxy/upstream.cr:172:9 in 'read_loop'
> Apr  8 04:06:56 amqproxy[4647]:   from tmp/amqproxy/src/amqproxy/server.cr:74:7 in '->'
> Apr  8 04:06:56 amqproxy[4647]:   from usr/share/crystal/src/fiber.cr:146:11 in 'run'
> Apr  8 04:06:56 amqproxy[4647]:   from ???
> Apr  8 04:06:56 amqproxy[4647]: amq_proxy.client[remote_address: "127.0.0.1:54170"] Upstream error
> Apr  8 04:06:56 amqproxy[4647]: Error writing to upstream (AMQProxy::Upstream::WriteError)
> Apr  8 04:06:56 amqproxy[4647]:   from tmp/amqproxy/src/amqproxy/upstream.cr:176:9 in 'send'
> Apr  8 04:06:56 amqproxy[4647]:   from tmp/amqproxy/src/amqproxy/upstream.cr:60:11 in 'unassign'
> Apr  8 04:06:56 amqproxy[4647]:   from tmp/amqproxy/src/amqproxy/client.cr:48:13 in 'read_loop'
> Apr  8 04:06:56 amqproxy[4647]:   from tmp/amqproxy/src/amqproxy/server.cr:74:7 in '->'
> Apr  8 04:06:56 amqproxy[4647]:   from usr/share/crystal/src/fiber.cr:146:11 in 'run'
> Apr  8 04:06:56 amqproxy[4647]:   from ???
> ```
> 
> So far our only solution has been to either downgrade or bypass AMQProxy as it happens randomly and frequently.

Ok
Will try

**Comment by carlhoerberg** [comment]
Please try again with v2.0.0-rc.3!
