### ISSUE TITLE
Option to not send a `connection_close` on SIGTERM

### ISSUE THREAD

**Issue by mruell** [cloudamqp/amqproxy#170]
Hi there!

The way we use AMQProxy, we depend on it being able to perform a rolling restart (in a kubernetes cluster).
For that we send a SIGTERM to the AMQProxy.

This commit changed the SIGTERM behaviour though: https://github.com/cloudamqp/amqproxy/commit/98c0bc7bdc2509d62c2191bc3038ce8ddcb0563d (The `else` in L81 moved in `amqproxy.cr`)

Now the shutdown is not graceful anymore, since it does **not** only wait for all clients to disconnect voluntary, but sends a connection close message proactively to the clients.

According to the [AMQP reference](https://www.rabbitmq.com/amqp-0-9-1-reference), that means:
> After sending this method, any received methods except Close and Close-OK **MUST** be discarded. The response to receiving a Close after sending Close must be to send Close-Ok.

Since this is the official reference, it is also implemented like this in most AMQP client libraries and one can't ignore a connection close message. (See for example in the most popular [PHP AMQP client library](https://github.com/php-amqplib/php-amqplib/blob/d0027050d3f8e66ba4f5497719bfa3aaf922ee4a/PhpAmqpLib/Channel/AbstractChannel.php#L475))

That means one is not able to e.g. finish processing the current message before shutting down, but instead it's possible, that a worker is forced to shutdown while processing a message. This can lead to messages being processed multiple times.

As a quick fix (since we build from source anyway) we use this patch on the file `amqproxy/src/amqproxy.cr`

```diff
--- amqproxy_original.cr	2024-08-16 16:28:59
+++ amqproxy.cr	2024-08-16 16:36:12
@@ -90,14 +90,17 @@
       if first_shutdown
         first_shutdown = false
         server.stop_accepting_clients
-        server.disconnect_clients
         if @term_timeout >= 0
           spawn do
             sleep @term_timeout
+            server.disconnect_clients
+            sleep 5
             abort "Exiting with #{server.client_connections} client connections still open"
           end
         end
       else
+        server.disconnect_clients
+        sleep 5
         abort "Exiting with #{server.client_connections} client connections still open"
       end
     end
```

The solutions that come to my mind would be one of these:
- The changes above to be merged (which would be a breaking change though)
- Like other servers do, there could be multiple signals - e.g. a SIGTERM could send the connection close, while maybe SIGINT could be really graceful by not sending the connection close
- A CLI option, to change the SIGTERM behaviour of whether to send a connection close or not

Would be happy to hear what you think about this :)

Thanks a lot in advance and best,
Marvin

**Comment by carlhoerberg** [comment]
Ok, thank you for your feedback! It makes sense. We will look at this.

**Comment by orlandothoeny** [comment]
We experience the same issue.
As mentioned in https://github.com/cloudamqp/amqproxy/issues/112#issuecomment-2298557891 & https://github.com/cloudamqp/amqproxy/issues/112#issuecomment-2298576020

**Comment by spuun** [comment]
@orlandothoeny @mruell would #175 be a good solution for you?

**Comment by orlandothoeny** [comment]
@spuun Yes that looks like it would to the job

**Comment by mruell** [comment]
Hi @orlandothoeny 

that solution looks like it will work!

The way I understand the changes, there will be a new option, to wait after not accepting new connections anymore until we forcefully close them by sending a close message.

That's pretty much the same logic as the `terminationGracePeriodSeconds` property for kubernetes pods.
So if we set the AMQProxy grace period just a little lower that the pod grace period, the workers should have enough time to finish their work and reconnect to a not-terminating pod (they are reconnecting every 15 minutes in-between processing messages, to reconnect to servers accepting new connections).

Thanks for that and best,
Marvin

**Comment by intxcc** [comment]
sorry, last comment was supposed to mention @spuun
