### ISSUE TITLE
Install AMQProxy with Noble Numbat

### ISSUE THREAD

**Issue by TristanPouliquen** [cloudamqp/amqproxy#171]
Hello,

The release 24.04.1 has been made a week ago, allowing for a safe upgrade to Noble Numbat, the new LTS for Ubuntu.

However, it seems I cannot correctly install amqproxy from your sources for this new distribution.

When will it be ready?

**Comment by spuun** [comment]
Next release will also be built for 24.04. It will probably be available next week.

**Comment by spuun** [comment]
2.0.2 is available for 24.04 now!
