### ISSUE TITLE
Allow overriding `connection_name` with a different value

### ISSUE THREAD

**Issue by mrtus** [cloudamqp/amqproxy#187]
👋 

We'd like to have the ability to configure a connection name through an environment variable.

This way we can easily identify the connections with e.g. the K8S pod name.
Currently, it is configured so that it is AMQProxy + version https://github.com/cloudamqp/amqproxy/blob/main/src/amqproxy/upstream.cr#L235 and is thus displayed as 👇, which does not help us a lot to identify where the actual connection is coming from, without having to match IP addresses
![image](https://github.com/user-attachments/assets/7123e55b-434f-432a-8290-750163eea646)

**Comment by carlhoerberg** [comment]
ok! good suggestion!

**Comment by mrtus** [comment]
I can confirm this change works as expected ✅
