### ISSUE TITLE
AMQProxy keeps opening new connections

### ISSUE THREAD

**Issue by Radiergummi** [cloudamqp/amqproxy#24]
Since two weeks ago, we experience a problem where the connections opened by our amqproxy instance won't be closed, resulting in more and more open connections, up to the point where our CloudAMQP instance runs out of memory, effectively shutting our application down:
![Screenshot_20190904_092654](https://user-images.githubusercontent.com/6115429/64234256-33550f80-cef6-11e9-8add-9bd24c291c95.png)
The sharp drops are us deploying a new amqproxy version to Kubernetes, killing all connections during deployment (we're now on 0.4.0).

At this point, I'm not sure what exactly is happening. I suspect it's an issue with one of our services, but I've traced down every single commit in the relevant time frame and I couldn't find anything related to the lower-level queue components.
Our setup looks like the following:

```
CloudAMQP <----> Google Kubernetes
                        |
                     amqproxy
                        |
            +-----+-----+-----+-----+
          srv1   srv2  srv3  srv4  srvN
```

The services all use the [PHP AMQP Library](https://github.com/php-amqplib/php-amqplib) with a super lightweight abstraction on top. After we've noticed the problem, we even implemented a shutdown handler to explicitly close the connection under all circumstances, but to no avail.

The connections all look like the following in the RabbitMQ manager:

Virtual host | Name | Node | State | SSL / TLS | Protocol | Channels | Channel max | Client | From Client | To Client | Heartbeat | Connected at
-------------|------|------|-------|-----------|----------|----------|-------------|--------|-------------|-----------|-----------|-------------
XXX | 35.xxx.xxx.xxx:2113 | rabbit@XXX-01 | running | ○ | AMQP 0-9-1 | 0 | 0 | AMQProxy0.4.0 | 0iB/s | 0iB/s |   | 22:06:372019-09-03
XXX | 35.xxx.xxx.xxx:32902 | rabbit@XXX-01 | running | ○ | AMQP 0-9-1 | 0 | 0 | AMQProxy0.4.0 | 0iB/s | 0iB/s |   | 08:37:022019-09-04
XXX | 35.xxx.xxx.xxx:33072 | rabbit@XXX-01 | running | ○ | AMQP 0-9-1 | 0 | 0 | AMQProxy0.4.0 | 0iB/s | 0iB/s |   | 02:28:202019-09-04
XXX | 35.xxx.xxx.xxx:33196 | rabbit@XXX-02 | running | ○ | AMQP 0-9-1 | 0 | 0 | AMQProxy0.4.0 | 0iB/s | 0iB/s |   | 00:38:142019-09-04
XXX | 35.xxx.xxx.xxx:33248 | rabbit@XXX-01 | running | ○ | AMQP 0-9-1 | 0 | 0 | AMQProxy0.4.0 | 0iB/s | 0iB/s |   | 03:26:462019-09-04
XXX | 35.xxx.xxx.xxx:33528 | rabbit@XXX-01 | running | ○ | AMQP 0-9-1 | 0 | 0 | AMQProxy0.4.0 | 0iB/s | 0iB/s |   | 17:20:152019-09-03

The AMQProxy logs contain lots and lots of entries like the following:
```
Error reading from upstream: #<Errno:Error reading socket: Bad file descriptor>
```

**Is there anything we can do to prevent this excessive connection spawning?**

**Comment by carlhoerberg** [comment]
can replicate, working on a fix

**Comment by carlhoerberg** [comment]
please try 0.4.1

**Comment by Radiergummi** [comment]
Hey Carl, thank you for the response. Sadly, this does not appear to fix the problem. We still see the bad file descriptor messages in the GCP logs, connection count seems to be rising again.  
Please let me know if I can help you debugging this issue.

**Comment by carlhoerberg** [comment]
ok! new 0.4.2 is out

**Comment by carlhoerberg** [comment]
the log lines you're showing seems to suggest that the whole server crashed and then restarted. A new 0.4.3 is out and handles connection disruptions in another way. Please open a new issue if it still reports abruptly closed connections.
