### ISSUE TITLE
Memory Leak in 0.4.2

### ISSUE THREAD

**Issue by twispt** [cloudamqp/amqproxy#25]
In our QA environment, over the course of two hours the proxy process rose to over 2GB of memory consumed before crashing.

0.4.0 does not seem to exhibit the issue. 0.4.1 does not work with my application, so I'm not able to confirm that the leak was introduced there or not.

Steps to reproduce:
1. Produce messages on a loop through amqproxy v0.4.2 using the produce.php file in the attached tar.
`while : ; do php producer.php proxy ; done`
2. View the process in top, noting that the amount of memory consumed always increases over time, and memory is never released.

I performed the above steps simultaneously to both 0.4.0 and 0.4.2 for 30 minutes or so, resulting in the below screenshot of top, note the VIRT column.
![image](https://user-images.githubusercontent.com/2292025/64736794-21084200-d4b1-11e9-89b3-2d085840d3c4.png)

This screenshot is a consumer host that has been running the proxy for about 2 hours.
![image](https://user-images.githubusercontent.com/2292025/64737143-cfac8280-d4b1-11e9-8a93-5f43bf7b7ce4.png)

[bernard_test.tar.gz](https://github.com/cloudamqp/amqproxy/files/3602790/bernard_test.tar.gz)

**Comment by carlhoerberg** [comment]
Thanks! Will look into it later today

**Comment by carlhoerberg** [comment]
Please try 0.4.3

**Comment by carlhoerberg** [comment]
you're welcome to open the issue again if you don't find 0.4.3 satisfactory.

**Comment by twispt** [comment]
Looks to be fixed!  Thanks, Carl!
