### ISSUE TITLE
OpenSSL VerifyMode

### ISSUE THREAD

**Issue by iarlyy** [cloudamqp/amqproxy#26]
I'm facing a problem that amqproxy is falling when verifying the upstream certificate

```
#<OpenSSL::SSL::Error:SSL_connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed>
```

is there a way to go around this? (disabling the verification would work well in my case)

**Comment by carlhoerberg** [comment]
ok, yes, just pass `OpenSSL::SSL::Context::Client.insecure` as `context` parameter here: https://github.com/cloudamqp/amqproxy/blob/master/src/amqproxy/upstream.cr#L26

but not some configuration for it too, can take a stab at it later

**Comment by iarlyy** [comment]
I've tried a new strategy, instead of using the pre-built release available here, i decided to build it fresh in the target instance(Amazon Linux 2 - ami-040ba9174949f6de4) and it seems it passed the certificate problem, but thanks for the heads up!

Not sure whether it would make sense to have a flag to allow insecure upstream.

**Comment by carlhoerberg** [comment]
That’s interesting, so the cert that you have on the upstream server, which cert is the root cert?

Maybe it’s because the precomplied release is built on ubuntu, with a different path to the cert root storage. Should probably start doing dynamic builds, for each distribution.
