### ISSUE TITLE
Memory leak in 0.4.4

### ISSUE THREAD

**Issue by jamesmcminn96** [cloudamqp/amqproxy#28]
In version `0.4.4` there is a still a memory leak similar to https://github.com/cloudamqp/amqproxy/issues/25 It is leaking at ~40kbps.

This is a memory usage graph between `0.4.0` & `0.4.4`
<img width="1243" alt="mem_leak" src="https://user-images.githubusercontent.com/3772113/72854254-ea1c2580-3d07-11ea-89a7-3f2cbdecd7d4.png">

**Comment by PavelvKalinin** [comment]
![image](https://user-images.githubusercontent.com/37908569/72878165-1f724480-3d03-11ea-9eb7-1cefe7a96fcd.png)

**Comment by carlhoerberg** [comment]
Hmm, I'm not able to replicate on os x, by repeatedly open a connection, declare a queue and publish a message on it. How do you use it? What kind of load?

**Comment by PavelvKalinin** [comment]
uname -a
`Linux worker-monolith-0 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux`

php -v
```
PHP 7.1.33-2+0~20191128.28+debian9~1.gbpc60685 (cli) (built: Nov 28 2019 07:44:58) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.33-2+0~20191128.28+debian9~1.gbpc60685, Copyright (c) 1999-2018, by Zend Technologies
```

on this server we run php workers 
workers connect to amqproxy

```
netstat -plan|grep -E 'amqproxy'|wc -l
160
netstat -plan|grep -E '1026|1027'|wc -l
158
```

**Comment by jamesmcminn96** [comment]
![image](https://user-images.githubusercontent.com/3772113/72884784-d0f09480-3d5a-11ea-8c10-0611c9a19324.png)

Strangely, after about an hour and a half of growing, the memory usage settled. The pattern of usage hadn't changed.

We're using it to provide TLS for one of our producing services. No more than around 30 messages per second across 4 queues. From what I can gather the connections between the proxy & rabbit are almost always reused.

Potentially the issue is in TLS connections to the upstream rabbit server?

I'll try reproducing locally. In production we're running from the Dockerfile in this repo on a 4.14 kernel.

**Comment by carlhoerberg** [comment]
Ok, trying to replicate with TLS then

**Comment by carlhoerberg** [comment]
Couldn't replicate with TLS either, at least not on a linux 5.3.0 machine. Found some other issues though that i'm working on.

**Comment by carlhoerberg** [comment]
Is this still an issue in 0.4.6?

**Comment by gnumoksha** [comment]
I can confirm the existence of a memory leak in version 0.4.4 running on linux kernel 5.3.0-1033-aws. The connection does not use TLS. After closing all connections, amqproxy did not free the memory.

I will update to the latest version (v0.4.8 ), but the CHANGELOG does not show any memory-related change.

**Comment by pshanoop** [comment]
latest  master has same issue.

**Comment by carlhoerberg** [comment]
Would be great very helpful if anyone observing this issue could perform a tcpdump:
```
tcpdump -s 0 port 5672 or 5673 -i eth0 -w amqproxy.pcap
```
and email it to me at carl@84codes.com

**Comment by gnumoksha** [comment]
> Would be great very helpful if anyone observing this issue could perform a tcpdump:
> 
> ```
> tcpdump -s 0 port 5672 or 5673 -i eth0 -w amqproxy.pcap
> ```
> 
> and email it to me at [carl@84codes.com](mailto:carl@84codes.com)

I have sent one dump to you.

Also, I'm experiencing the memory leak in amqproxy 0.5.0 and rabbitmq 3.8.9. I can't see the [relation between the number of connections and the amount of used memory](https://github.com/cloudamqp/amqproxy/issues/43#issuecomment-740587290).
