### ISSUE TITLE
Help, my connections are not being reused.

### ISSUE THREAD

**Issue by chinyoongtat** [cloudamqp/amqproxy#29]
Hello,

My application is running on the php-amqplib library. I start my amqproxy instance via the command below in ubuntu terminal.

    amqproxy -l 127.0.0.1 -p 5674 amqp://127.0.0.1 -d

my code in php establishes the connection like this, 

    $this->connection = new AMQPStreamConnection($connection, 5674, $this->user, $this->password);

I then proceed to create 2 instances of the code above on 2 separate terminal sessions.
Upon viewing the management UI connection tab, I see 2 connections. I am expecting 1 only.

Please help.

**Comment by carlhoerberg** [comment]
that's expected, the proxy will keep "long-lived" connections to the rabbitmq server, for clients that can't keep long lived connections (eg. PHP when publishing as part of a page view)
