### ISSUE TITLE
how can i determine if im actually getting cached connections?

### ISSUE THREAD

**Issue by waypointsoftware** [cloudamqp/amqproxy#3]
I installed the service and configured it to hit my rabbitmq server, and my code is configured to hit the amqproxy (and working)

however i dont see any performance increase and see a bunch of this in the system.log:

Client connection closed from [::ffff:127.0.0.1]:36414
Client connection accepted from [::ffff:127.0.0.1]:36422

So can I confirm 1 way or another that its actually reusing a connection?

**Comment by carlhoerberg** [comment]
You can look in the RabbitMQ managemnet interface under the Connections tab
