### ISSUE TITLE
Unknown error (read_loop)

### ISSUE THREAD

**Issue by CaioPaiola** [cloudamqp/amqproxy#33]
Anybody know this error?

![error](https://i.imgur.com/QqKdMxc.png)

**Comment by johanrhodin** [comment]
Hi, which version of AMQProxy are you using?

**Comment by CaioPaiola** [comment]
I use the last release.
 
![Screen Shot 2020-05-16 at 00 32 00](https://user-images.githubusercontent.com/1007067/82109498-ccd2f300-970c-11ea-8728-bb21d0422d97.png)

**Comment by johanrhodin** [comment]
There is a 0.4.5.

**Comment by CaioPaiola** [comment]
I'll try this version.

**Comment by CaioPaiola** [comment]
In the last version this trouble not happening anymore. Thanks a lot.

**Comment by pastatem** [comment]
I have the same problem in new version (0.4.5)
```
Unhandled exception in spawn: End of file reached (IO::EOFError)
  from ???
  from /usr/share/crystal/src/gc/boehm.cr:110:5 in 'read_loop'
  from /usr/share/crystal/src/fiber.cr:255:3 in 'run'
  from ???
```
Crystal version:
```
Crystal 0.34.0 [4401e90f0] (2020-04-06)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by averyanoff** [comment]
2021-07-21 17:49:26 +03:00: Error reading from upstream: End of file reached (IO::EOFError)
  from /usr/local/src/amqproxy/lib/amq-protocol/src/amq/protocol/frames.cr:21:32 in 'read_loop'
  from /usr/local/src/crystal-1.0.0-1/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???

./amqproxy -v
0.5.6
