### ISSUE TITLE
End of file reached (IO::EOFError)

### ISSUE THREAD

**Issue by pastatem** [cloudamqp/amqproxy#34]
I have issue #33 reproduced in the latest version (0.4.5)
```
Unhandled exception in spawn: End of file reached (IO::EOFError)
  from ???
  from /usr/share/crystal/src/gc/boehm.cr:110:5 in 'read_loop'
  from /usr/share/crystal/src/fiber.cr:255:3 in 'run'
  from ???
```
Crystal version:
```
Crystal 0.34.0 [4401e90f0] (2020-04-06)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```

This problem is reproduced only for consumer connections. The producers work great.

**Comment by carlhoerberg** [comment]
Do you happen to have code that can reproduce it?

**Comment by pastatem** [comment]
I just started consumers using rabbitmq-cli-consumer. A few seconds after processing the message, an error occurred.
As I can see in the latest version (0.4.6) everything works fine.

**Comment by carlhoerberg** [comment]
Ok, glad to hear that!
