### ISSUE TITLE
Docker build failed

### ISSUE THREAD

**Issue by evansjenny** [cloudamqp/amqproxy#35]
`docker build -t amqproxy:v0.4.5 https://github.com/cloudamqp/amqproxy.git#v0.4.5
Sending build context to Docker daemon  70.14kB
Step 1/8 : FROM crystallang/crystal
 ---> 4687b017edf3
Step 2/8 : WORKDIR /app
 ---> Using cache
 ---> 6ab8562c6b50
Step 3/8 : COPY . .
 ---> Using cache
 ---> 15a7f1d11032
Step 4/8 : RUN shards build --release --production
 ---> Running in e2c4d603cac8
Resolving dependencies
Fetching https://github.com/cloudamqp/amq-protocol.cr.git
Installing amq-protocol (0.3.6)
Building: amqproxy
Error target amqproxy failed to compile:
Showing last frame. Use --error-trace for full trace.

In lib/amq-protocol/src/amq/protocol/table.cr:227:32

 227 | private def skip_field : Int32
                                ^
Error: method must return Int32 but it is returning Int64
`

**Comment by carlhoerberg** [comment]
fixed with a `shards update`, master should be fine

**Comment by evansjenny** [comment]
Thank you!
