### ISSUE TITLE
Docker build failed

### ISSUE THREAD

**Issue by evansjenny** [cloudamqp/amqproxy#36]
$ git clone https://github.com/cloudamqp/amqproxy /tmp/amqproxy
Cloning into '/tmp/amqproxy'...
$ cd /tmp/amqproxy
$ docker build -t amqproxy:latest .
Step 1/8 : FROM crystallang/crystal
latest: Pulling from crystallang/crystal
d7c3167c320d: Pulling fs layer
131f805ec7fd: Pulling fs layer
322ed380e680: Pulling fs layer
6ac240b13098: Pulling fs layer
22da88a5d530: Pulling fs layer
6ac240b13098: Waiting
22da88a5d530: Waiting
322ed380e680: Verifying Checksum
322ed380e680: Download complete
131f805ec7fd: Verifying Checksum
131f805ec7fd: Download complete
d7c3167c320d: Verifying Checksum
d7c3167c320d: Download complete
6ac240b13098: Verifying Checksum
6ac240b13098: Download complete
d7c3167c320d: Pull complete
22da88a5d530: Verifying Checksum
22da88a5d530: Download complete
131f805ec7fd: Pull complete
322ed380e680: Pull complete
6ac240b13098: Pull complete
22da88a5d530: Pull complete
Digest: sha256:afd58df611c04807961539f884bbe8dfd25ea9fd54132cbea2c01f5475689ebd
Status: Downloaded newer image for crystallang/crystal:latest
 ---> ee810d01edd1
Step 2/8 : WORKDIR /app
 ---> Running in b5e32584d9af
Removing intermediate container b5e32584d9af
 ---> 99bff998ec9a
Step 3/8 : COPY . .
 ---> ba5593b5f51b
Step 4/8 : RUN shards build --release --production
 ---> Running in 1f9eb895802c
Resolving dependencies
Fetching https://github.com/cloudamqp/amq-protocol.cr.git
Installing amq-protocol (0.3.12)
Building: amqproxy
Error target amqproxy failed to compile:
Showing last frame. Use --error-trace for full trace.
In lib/amq-protocol/src/amq/protocol/frames.cr:416:21
 416 | bytes += io.write_bytes(@reply_code, format)
             ^
Error: no overload matches 'Int64#+' with type Nil
Overloads are:
 - Int64#+(other : Int8)
 - Int64#+(other : Int16)
 - Int64#+(other : Int32)
 - Int64#+(other : Int64)
 - Int64#+(other : Int128)
 - Int64#+(other : UInt8)
 - Int64#+(other : UInt16)
 - Int64#+(other : UInt32)
 - Int64#+(other : UInt64)
 - Int64#+(other : UInt128)
 - Int64#+(other : Float32)
 - Int64#+(other : Float64)
 - Number#+()
The command '/bin/sh -c shards build --release --production' returned a non-zero code: 1

**Comment by carlhoerberg** [comment]
thanks, fixed in master
