### ISSUE TITLE
Question: How are channels handled by the proxy?

### ISSUE THREAD

**Issue by chrisharrison** [cloudamqp/amqproxy#37]
If I have a PHP page:
```
<?php

echo 'Hello, welcome to my lovely website.';

$connection = new \AMQPConnection(...);
$channel = new \AMQPChannel($connection);
$exchange = new \AMQPExchange($channel);
$exchange->publish(...);

?>
```

Will the channel get reused on the second execution of this code?

Could I get the proxy to reuse the channel by setting the channel ID when I open the channel? (I don't believe the PECL version allows this but other PHP libraries do).

**Comment by spuun** [comment]
Channels are reused when possible, as stated in the README:

> Only "safe" channels are reused, that is channels where only Basic Publish or Basic Get (with no_ack) has occurred. Any channels who has subscribed to a queue will be closed when the client disconnects. However, the connection to the upstream AMQP server are always kept open and can be reused.

**Comment by chrisharrison** [comment]
I get that channels are kept open and reused. But is that by channel ID? Or when you do `new \AMQPExchange($channel);` in PHP it just re-uses any random channel?

**Comment by spuun** [comment]
It's random. The client may end up on another connection.

**Comment by chrisharrison** [comment]
Thank you that's very useful.
