### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by amramtamir** [cloudamqp/amqproxy#4]
If I want to use it in a Containerized environment like Kubernetes or DC/OS , what is the best practice :
1) having 1 centralized proxy for all the micro services ?
2) having an embedded proxy inside the service image?

Thanks

**Comment by carlhoerberg** [comment]
1 centralized On Jul 6, 2018 18:09, amramtamir <notifications@github.com> wrote:If I want to use it in a Containerized environment like Kubernetes or DC/OS , what is the best practice :
having 1 centralized proxy for all the micro services ?having an embedded proxy inside the service image?
Thanks

**Comment by amramtamir** [comment]
OK , will give it a try, thanks!

**Comment by arealmaas** [comment]
Late to the party, but why is that the case @carlhoerberg ?

**Comment by carlhoerberg** [comment]
No, that is absolutely fine.
