### ISSUE TITLE
Newline in logfile

### ISSUE THREAD

**Issue by ameenross** [cloudamqp/amqproxy#42]
I noticed that AMQProxy logs have `\r` as newline. This is very annoying when trying to grep, count lines and whatnot on linux. It means that the newlines have to be converted to `\n` first. Actually, I just checked again and I'm also seeing some `\n\r` scattered around, which is *really* exotic. Anyone running AMQProxy on BBC Micro?

I don't know anything about Crystal and I don't wanna, but PHP has a builtin constant for a platform-specific newline: `PHP_EOL`. This will be `\n` on linux and `\r\n` on windows. Although to be fair, does AMQProxy even target windows at all? If not, search/replace `\r` with `\n` in the codebase is a solution.

**Comment by carlhoerberg** [comment]
Fixed in master and v0.5.0
