### ISSUE TITLE
[Question] Possible to limit the number of connections to RabbitMQ?

### ISSUE THREAD

**Issue by mboutet** [cloudamqp/amqproxy#43]
I took a look at the code (note: I have zero experience of Crystal), but could not find anything related to configuring this.

I'm asking this since RabbitMQ metrics are indicated that the number of connections grows endlessly until amqproxy gets OOM killed by k8s. The metrics show thousands of connections on RabbitMQ's side but I know I don't have that many clients connecting to RabbitMQ (and each client is limited in the number of connections it can opened simultaneously).

Having such a configurable parameter would help control the proxy's pool size according to known usage pattern. For instance, if I know that I'll have at most 200 clients each with 1 active connection, I'll limit the proxy to 250 or so.

Thank you in advance.

**Comment by carlhoerberg** [comment]
That would be a bandaid on a bleeding wound, the connection leak should be
fixed first, a connection limit would just move the problem to your clients
instead, they would be rejected connections when the limit is reached. The
question is why connections aren't being reused and pile up instead. Are
you able to do a tcpdump on the amqproxy node?

**Comment by mboutet** [comment]
I managed to run `tcpdump -v -i eth0` in a side container (`ubuntu:20.04`) in the proxy's pod and pipe it to a file on my machine. The content of this file is for a few seconds only. Also, it does not appear in this file, but if I run the same command using `kubectl exec` and interrupt it with ctrl+c, it prints:
```
17960 packets captured
18749 packets received by filter
779 packets dropped by kernel
```

[amqproxy-tcpdump1.log](https://github.com/cloudamqp/amqproxy/files/5645710/amqproxy-tcpdump1.log)

For reference, here is the memory usage when the load of my system is relativement idle:
![image](https://user-images.githubusercontent.com/52334444/101218988-fd9b5b00-3651-11eb-8924-636e4fa6f01c.png)

On `v0.4.8`, I did not experienced this memory increase when idle, but it would otherwise increase as soon as more clients connect and never decrease even after the load is gone. I use auto-scaling and clients are relatively short-lived.

**Comment by carlhoerberg** [comment]
Thanks! Will take a look

**Comment by carlhoerberg** [comment]
oh, actually, a pcap file would've been much better: 
```
tcpdump -s 0 port 5672 or 5673 -i eth0 -w amqproxy.pcap
```
although all data in the traffic will then be visible (actually message data), i don't know if you want/are able to share that publicly. If you're willing to share it with just me you can email the pcap file to carl@84codes.com

**Comment by mboutet** [comment]
Ok, let me look into it right now.

Also, nevermind what I said about `v0.4.8` previously: it also has the increasing memory usage

**Comment by mboutet** [comment]
I think I found the culprit: one of the client is the one responsible for scaling some workloads based on queue length. To do this, it uses "Queue declare" a lot. I'll send you the pcap file shortly, but inspecting it in wireshark, I can see a lot of `Queue.Declare`. Also, for this test, I made all the other clients directly connect to RabbitMQ except for the client responsible for the auto-scaling, so all you have is the packets of this client.

**Comment by mboutet** [comment]
I sent it to your email.

**Comment by gnumoksha** [comment]
> [...] increase as soon as more clients connect and never decrease even after the load is gone.

it seems related to https://github.com/cloudamqp/amqproxy/issues/28

**Comment by carlhoerberg** [comment]
Thank you for the pcap file @mboutet! But I can conclude that both the server and the client are behaving correct, the problem is that you don't close the connections in your code. Both the server and client connection continue to send heartbeats, because the process starting the connection is still alive, you should check your code and make sure that the AMQP connection is terminated once you're done using it. An ever increasing connection count will use memory, both on the server and client side, but adding a connection limit won't help here, once you reach the limit you will have thousands of idle open connections, but won't be able to open new ones, efficiently limiting memory usage yes, but also hindering any kind of useful work.

**Comment by mboutet** [comment]
Thanks @carlhoerberg for the help in identifying the problem. I opened an issue in the project that is opening all these connections.

If I understand correctly, the `Connection.Close reply=Pooled connection closed due to inactivity` in the pcap is telling that the connection is being closed by the proxy/RabbitMQ and not the client, is that is? So, the client is effectively never closing its connections?
