### ISSUE TITLE
Heartbeat from proxy to rabbitmq server

### ISSUE THREAD

**Issue by aportnov77** [cloudamqp/amqproxy#44]
We are try to use amqproxy in our php stack to avoid performance lack and avoid of ghost connections on rabbitmq server.
But if we have the network issue and rabbitmq is not reachable for proxy then there would be ghost connections from our consumers. That is caused impossibility to send heartbeat by proxy to rabbitmq.
Enabling possibility to send heartbeat to amqp proxy will solve this issue.
Thanks

**Comment by carlhoerberg** [comment]
i see, yes, let's enable that

**Comment by carlhoerberg** [comment]
But better yet, enable TCP keepalive on the server: 

in the rabbit config:

tcp_listen_options.keepalive=true

and then in sysctl: 
net.ipv4.tcp_keepalive_time=30
net.ipv4.tcp_keepalive_intvl=10
net.ipv4.tcp_keepalive_probes=3

https://www.rabbitmq.com/networking.html#tcp-keepalives

**Comment by carlhoerberg** [comment]
It's much more relaible than AMQP heartbeats, because it happens in the kernel

**Comment by aportnov77** [comment]
@carlhoerberg thank you!

**Comment by wxbacy** [comment]
when I use aliyun amqp service, it is useless to set heartbeat on connect or set /etc/sysctl.conf
net.ipv4.tcp_keepalive_time=30
net.ipv4.tcp_keepalive_intvl=10
net.ipv4.tcp_keepalive_probes=3
I use amqp client is php amqp extension

**Comment by wxbacy** [comment]
aliyun amqp not support tcp keepalive

**Comment by carlhoerberg** [comment]
Can you connect at all? Looks like Aliyun AMQP only support AMQP 1.0. `amqproxy` only supports AMQP 0-9-1

**Comment by carlhoerberg** [comment]
btw, doesn't matter if the server supports TCP keepalive or not. the client can always enable TCP keepalive. It's described here: https://tldp.org/HOWTO/TCP-Keepalive-HOWTO/overview.html

**Comment by wxbacy** [comment]
it is always consumer connect out after consumer connect A few minutes，I config this
net.ipv4.tcp_keepalive_time=30
net.ipv4.tcp_keepalive_intvl=10
net.ipv4.tcp_keepalive_probes=3
and ask aliyun for help, the answer aliyun amqp not support tcp keepalive,

**Comment by wxbacy** [comment]
when I not use amqproxy, direct connect Aliyun AMQP, connect config heartbeat = 30,it works well

**Comment by carlhoerberg** [comment]
can you show the full error message?

**Comment by dentarg** [comment]
> https://hub.docker.com/repository/docker/cloudamqp/amqproxy

The public URL is https://hub.docker.com/r/cloudamqp/amqproxy

**Comment by wxbacy** [comment]
it works@carlhoerberg
