### ISSUE TITLE
Setup in Ubuntu

### ISSUE THREAD

**Issue by mortillan** [cloudamqp/amqproxy#48]
Hi,

I need help for setting this up in Ubuntu. Followed installation instruction in here https://github.com/cloudamqp/amqproxy
I'm using pika python as client library.

I'm getting this error at journalctl of amqproxy.service

amqproxy[9360]: Upstream error for user '********' to vhost '*********': #<AMQProxy::Upstream::Error:Cannot establish connection to upstream>

I edited the upstream of amqproxy.service to point to my CloudAMQP URL by running this command

sudo systemctl edit --full amqproxy.service

then I am pointing my client to connect to localhost:5673 and providing the username, password and vhost in the upstream server.

What am I doing wrong? Thanks in advance.

**Comment by carlhoerberg** [comment]
Vhost '*', is that correct?

Are you able to connect normally to the server? What does the URI in the
systemd file look like now?

**Comment by mortillan** [comment]
I just changed it to hide my vhost.. but that shows the vhost and user provided by CloudAMQP.

Here is the current value of amqproxy.service file

![image](https://user-images.githubusercontent.com/7253957/111853099-7b127f00-8954-11eb-82b9-6b00419eb554.png)

**Comment by mortillan** [comment]
I just changed them to hide my vhost and user... It's real value is the one provided by CloudAMQP.

Here is the current settings in amqproxy.service

![image](https://user-images.githubusercontent.com/7253957/111853169-c9278280-8954-11eb-94e6-83360f4e0c98.png)

**Comment by carlhoerberg** [comment]
Ok, you're providing the username and password and vhost in the client TO the localhost.5673 server right? so the url in pika looks like `amqp://myuser:mypassword@localhost:5673/myvhost` ?

**Comment by carlhoerberg** [comment]
Closied due to no response
