### ISSUE TITLE
Systemctl log Error

### ISSUE THREAD

**Issue by wxbacy** [cloudamqp/amqproxy#49]
amqproxy[1367]: 2021-03-22 15:58:49 +08:00: Receiving AMQ::Protocol::Frame::Channel::Close(@channel=1, @bytesize=96, @reply_code=404, @reply_text="ExchangeNotExist, ReqId:60584E39433839BF6765A9DE, ErrorHelp[60584E39433839BF6765A9D6]", @classid=60, @methodid=40) but no client to delivery to
amqproxy[1367]: 2021-03-22 16:00:50 +08:00: Receiving AMQ::Protocol::Frame::Channel::Close(@channel=1, @bytesize=96, @reply_code=404, @reply_text="ExchangeNotExist, ReqId:60584EB2433839BF67671EC5, ErrorHelp[60584EB2433839BF67671EBB]", @classid=60, @methodid=40) but no client to delivery to
amqproxy[1367]: 2021-03-22 16:00:57 +08:00: Receiving AMQ::Protocol::Frame::Channel::Close(@channel=1, @bytesize=96, @reply_code=404, @reply_text="ExchangeNotExist, ReqId:60584EB93937334A54B4D7D8, ErrorHelp[60584EB93937334A54B4D7D3]", @classid=60, @methodid=40) but no client to delivery to
amqproxy[1367]: 2021-03-22 16:01:33 +08:00: Receiving AMQ::Protocol::Frame::Basic::QosOk(@channel=1, @bytesize=4) but no client to delivery to
amqproxy[1367]: 2021-03-22 16:01:33 +08:00: Upstream closed connection: ChannelNotFind
amqproxy[1367]: 2021-03-22 16:01:33 +08:00: Upstream connection closed when returned
amqproxy[1367]: 2021-03-22 16:02:24 +08:00: Receiving AMQ::Protocol::Frame::Channel::Close(@channel=1, @bytesize=96, @reply_code=404, @reply_text="ExchangeNotExist, ReqId:60584F10344230DF117686FC, ErrorHelp[60584F10344230DF117686F4]", @classid=60, @methodid=40) but no client to delivery to
amqproxy[1367]: 2021-03-22 16:03:00 +08:00: Receiving AMQ::Protocol::Frame::Channel::Close(@channel=1, @bytesize=96, @reply_code=404, @reply_text="ExchangeNotExist, ReqId:60584F34383038457786EFA4, ErrorHelp[60584F34383038457786EF9B]", @classid=60, @methodid=40) but no client to delivery to
amqproxy[1367]: 2021-03-22 16:03:26 +08:00: Receiving AMQ::Protocol::Frame::Channel::Close(@channel=1, @bytesize=96, @reply_code=404, @reply_text="ExchangeNotExist, ReqId:60584F4E433839BF6768CDB2, ErrorHelp[60584F4E433839BF6768CDAC]", @classid=60, @methodid=40) but no client to delivery to
amqproxy[1367]: 2021-03-22 16:05:49 +08:00: Receiving AMQ::Protocol::Frame::Channel::Close(@channel=1, @bytesize=96, @reply_code=404, @reply_text="ExchangeNotExist, ReqId:60584FDD433745A76B0C6DAE, ErrorHelp[60584FDD433745A76B0C6D9F]", @classid=60, @methodid=40) but no client to delivery to

Such As this

**Comment by wxbacy** [comment]
not alaways，There is a probability happen,exchange is totally exists

**Comment by wxbacy** [comment]
amqproxy[1367]: 2021-03-22 20:15:10 +08:00: Receiving AMQ::Protocol::Frame::Basic::Cancel(@channel=1, @bytesize=12, @consumer_tag="sgen-1", @no_wait=true) but no client to delivery to
amqproxy[1367]: 2021-03-22 20:15:10 +08:00: Receiving AMQ::Protocol::Frame::Basic::Cancel(@channel=1, @bytesize=12, @consumer_tag="sgen-1", @no_wait=true) but no client to delivery to
amqproxy[1367]: 2021-03-22 20:15:10 +08:00: Receiving AMQ::Protocol::Frame::Basic::Cancel(@channel=1, @bytesize=12, @consumer_tag="sgen-1", @no_wait=true) but no client to delivery to

**Comment by wxbacy** [comment]
![R4I_ZSO$W I5 NU3GTQ MDJ](https://user-images.githubusercontent.com/20201380/113082086-6bc0ea80-920c-11eb-8545-381c8f4e5acf.png)
![FS8VVOC52`9JJV1(8U}DW26](https://user-images.githubusercontent.com/20201380/113082095-6cf21780-920c-11eb-82fe-d6b1ca17df58.png)

Error log on my product environ, what is it mean? it is rabbitmq error or amqproxy error

**Comment by carlhoerberg** [comment]
Please try with the latest release and reopen if still not fixed.
