### ISSUE TITLE
Installing Crystal failed during Vagrant machine provisioning

### ISSUE THREAD

**Issue by dsch** [cloudamqp/amqproxy#53]
## Reproducing steps: 
`vagrant up debian9`

## Output
```
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.Al6wzHKRRU/gpg.1.sh --keyserver keys.gnupg.net --recv-keys 09617FD37CC06B54
gpg: keyserver receive failed: No name
GPG error: http://dist.crystal-lang.org/apt crystal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 09617FD37CC06B54
The repository 'http://dist.crystal-lang.org/apt crystal InRelease' is not signed.
```
Is this still supported?
Should the vagrant file follow the installation instruction on crystal-lang.org? https://crystal-lang.org/install/on_debian/#official-crystal-deb-repository

**Comment by carlhoerberg** [comment]
The `Vagrantfile` isn't updated in >2 years so yeah, definitely outdated, it doesn't even seem to have compiled the amqproxy, I think it was used once upon a time for building packages, but we're using docker/podman for that nowadays.

**Comment by carlhoerberg** [comment]
What would you like to use it for? Cannot use the `Dockerfile` instead?

**Comment by dsch** [comment]
I used it to pack amqproxy for Debian 9 (Stretch) which worked back in April 21. Now I tried to pack it for Debian 10 (Buster) by adding a VM definition for debian10, which failed because of the change in the Crystal installation process.

I also tried to lcx_deb script, but could not make work lcx work on my machine.

I solved the problem for me by updating the Vagrantfile. Are you interested in a PR? Otherwise you could close this issue.

**Comment by carlhoerberg** [comment]
We now build debian packages using github actions, and upload to packagecloud: https://packagecloud.io/app/cloudamqp/amqproxy/search?dist=debian%2Fbuster
