### ISSUE TITLE
Packagecloud repository doesn't support debian buster

### ISSUE THREAD

**Issue by rauanmayemir** [cloudamqp/amqproxy#56]
I couldn't set up amqproxy under debian buster even after looking up debian bash script. It seems to only account for debian stretch.

**Comment by madhancock** [comment]
@carlhoerberg Any chance we can get an update on this one? Currently looks like the only option for install of this is manual on Debian.

**Comment by rauanmayemir** [comment]
I’ve thought about building manually, but crystal is only on alpine. (older versions support jessie)

**Comment by carlhoerberg** [comment]
I will take a look at this next week. Need to modify the packages.yml
GitHub workflow to use docker images instead

**Comment by carlhoerberg** [comment]
Fixed! https://packagecloud.io/app/cloudamqp/amqproxy/search?dist=debian%2Fbuster
