### ISSUE TITLE
Not able to recreate upstream connection 

### ISSUE THREAD

**Issue by umolina** [cloudamqp/amqproxy#6]
I'm running the proxy on a docker container and found that if the upstream rabbitmq cluster closes the connection or is not available, the proxy is not able to reconnect. The client connection is constantly being accepted and closed while the proxy errors trying to read from the upstream.

Is there something I'm doing wrong here?

See the log below, thanks

> Proxy upstream: rabbitmq:5672 
Proxy listening on [::]:5673
Client connection accepted from [::ffff:172.23.0.18]:38426
Connected to upstream 172.23.0.2:5672
Client connection closed from [::ffff:172.23.0.18]:38426
Client connection accepted from [::ffff:172.23.0.18]:38434
Client connection accepted from [::ffff:172.23.0.16]:56310
Connected to upstream 172.23.0.2:5672
Client connection accepted from [::ffff:172.23.0.18]:38468
Connected to upstream 172.23.0.2:5672
Client connection accepted from [::ffff:172.23.0.16]:56338
Connected to upstream 172.23.0.2:5672
Client connection accepted from [::ffff:172.23.0.16]:56368
Connected to upstream 172.23.0.2:5672
Client connection accepted from [::ffff:172.23.0.18]:38510
Connected to upstream 172.23.0.2:5672
Unhandled exception in spawn:
cast from AMQProxy::AMQP::Connection::Close to AMQProxy::AMQP::Channel::CloseOk failed, at /var/amqpproxy/src/amqproxy/upstream.cr:101:22:101 (TypeCastError)
Client connection closed from [::ffff:172.23.0.18]:38434
  from var/amqpproxy/src/amqproxy/upstream.cr:100:11 in '->'
  from var/amqpproxy/src/amqproxy/pool.cr:255:3 in 'handle_connection'
  from var/amqpproxy/src/amqproxy/server.cr:41:13 in '->'
  from usr/share/crystal/src/fiber.cr:255:3 in '???'
  from ???
Error reading from upstream: #<Errno:Error reading socket: Connection reset by peer>
Unhandled exception in spawn:
cast from AMQProxy::AMQP::Connection::Close to AMQProxy::AMQP::Channel::CloseOk failed, at /var/amqpproxy/src/amqproxy/upstream.cr:101:22:101 (TypeCastError)
Client connection closed from [::ffff:172.23.0.16]:56310
  from var/amqpproxy/src/amqproxy/upstream.cr:100:11 in '->'
  from var/amqpproxy/src/amqproxy/pool.cr:255:3 in 'handle_connection'
  from var/amqpproxy/src/amqproxy/server.cr:41:13 in '->'
  from usr/share/crystal/src/fiber.cr:255:3 in '???'
  from ???
Error reading from upstream: #<Errno:Error reading socket: Connection reset by peer>
Error reading from upstream: #<Errno:Error reading socket: Connection reset by peer>
Client connection closed from [::ffff:172.23.0.18]:38468
Error reading from upstream: #<Errno:Error reading socket: Connection reset by peer>
Client connection closed from [::ffff:172.23.0.16]:56338
Error reading from upstream: #<Errno:Error reading socket: Connection reset by peer>
Client connection closed from [::ffff:172.23.0.16]:56368
Error reading from upstream: #<Errno:Error reading socket: Connection reset by peer>
Client connection closed from [::ffff:172.23.0.18]:38510
Client connection accepted from [::ffff:172.23.0.18]:38520
Client connection closed from [::ffff:172.23.0.18]:38520
Client connection accepted from [::ffff:172.23.0.18]:38524
Client connection closed from [::ffff:172.23.0.18]:38524
Client connection accepted from [::ffff:172.23.0.18]:38536
Client connection closed from [::ffff:172.23.0.18]:38536
Client connection accepted from [::ffff:172.23.0.16]:56406
Client connection closed from [::ffff:172.23.0.16]:56406
Client connection accepted from [::ffff:172.23.0.18]:38546
Client connection closed from [::ffff:172.23.0.18]:38546
Client connection accepted from [::ffff:172.23.0.16]:56418
Client connection closed from [::ffff:172.23.0.16]:56418
Client connection accepted from [::ffff:172.23.0.18]:38558
Error sending to upstream: #<Errno:Error writing to socket: Broken pipe>
Client connection closed from [::ffff:172.23.0.18]:38558
Client connection accepted from [::ffff:172.23.0.18]:38564
Error sending to upstream: #<Errno:Error writing to socket: Broken pipe>
Client connection closed from [::ffff:172.23.0.18]:38564
Client connection accepted from [::ffff:172.23.0.16]:56432
Error sending to upstream: #<Errno:Error writing to socket: Broken pipe>
Client connection closed from [::ffff:172.23.0.16]:56432
Client connection accepted from [::ffff:172.23.0.18]:38574
Error sending to upstream: #<Errno:Error writing to socket: Broken pipe>
Client connection closed from [::ffff:172.23.0.18]:38574
Client connection accepted from [::ffff:172.23.0.18]:38580
Error sending to upstream: #<Errno:Error writing to socket: Broken pipe>
Client connection closed from [::ffff:172.23.0.18]:38580
Client connection accepted from [::ffff:172.23.0.18]:38584
Error sending to upstream: #<Errno:Error writing to socket: Broken pipe>
Client connection closed from [::ffff:172.23.0.18]:38584
Client connection accepted from [::ffff:172.23.0.18]:38588
Error sending to upstream: #<Errno:Error writing to socket: Broken pipe>
Client connection closed from [::ffff:172.23.0.18]:38588
Client connection accepted from [::ffff:172.23.0.18]:38592
Error sending to upstream: #<Errno:Error writing to socket: Broken pipe>

**Comment by carlhoerberg** [comment]
Thank you for reporting, fixed now
