### ISSUE TITLE
Missing new releases

### ISSUE THREAD

**Issue by gnumoksha** [cloudamqp/amqproxy#60]
[Last release is 0.5.0](https://github.com/cloudamqp/amqproxy/releases)
![image](https://user-images.githubusercontent.com/696797/142488518-e19c8ef8-39e3-47d1-9373-39155972f4b6.png)

[Last tag is 0.5.7](https://github.com/cloudamqp/amqproxy/tags)
![image](https://user-images.githubusercontent.com/696797/142488608-469714fc-8969-4d57-8097-4f7906879003.png)

**Comment by dentarg** [comment]
I added, but they don't have any binary attached to them.

There are Docker images published for them though: https://hub.docker.com/r/cloudamqp/amqproxy/tags

And packages published at https://packagecloud.io/cloudamqp/amqproxy
