### ISSUE TITLE
stale connections

### ISSUE THREAD

**Issue by aradhell** [cloudamqp/amqproxy#63]
Hello, once in a while I see queues are having some stale connections, for example:
I have only 3 consumers working at the moment but queue shows 5. And I constantly see 2 unack message and consumer staying there.

![image](https://user-images.githubusercontent.com/6387515/147354171-5bfe1c3b-77ee-4a67-b159-a2f8144a9d40.png)

![image](https://user-images.githubusercontent.com/6387515/147354252-b70331cb-098a-4ed6-9492-4450a45857ac.png)

php consumer lifetime is 1 hr. which is downloading a file per queue item. 

Thanks in advance for help!

**Comment by carlhoerberg** [comment]
Thank you for reporting, i believe this is fixed now
