### ISSUE TITLE
alternative Docker registry

### ISSUE THREAD

**Issue by philipp-hb** [cloudamqp/amqproxy#65]
Since Dockerhub introduced rate-limiting and the new license model: Are there any alternative registries where you push your image? If not, is it planned?

**Comment by dentarg** [comment]
No, and not planned as far as I know. 

What are the new rate limits? 
I don't think the license model change changed anything for images published to the registry, or did it?

Do you have any suggestions on alternative registries?

I think GitHub Packages container registry could be an option:

* https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
* https://docs.github.com/en/get-started/learning-about-github/githubs-products

cc @carlhoerberg

**Comment by philipp-hb** [comment]
Here is the documentation about rate limit: https://docs.docker.com/docker-hub/download-rate-limit/
And here the new licensing terms: https://docs.docker.com/subscription/
It is imho quite unclear what this exactly means for docker hub, but according to many articles, this means companies have to pay to be allowed to pull images from docker hub.

Most other projects provide their images now also on registries like quay.io (redhat), ghcr (github) or public ecr (aws)

**Comment by carlhoerberg** [comment]
Let us know when this becomes an actual problem and we can reconsider.
