### ISSUE TITLE
more verbose logs

### ISSUE THREAD

**Issue by alv91** [cloudamqp/amqproxy#67]
We have a lot of errors like that:

```
2022-02-14 13:34:35 UTC: Client connected: xxx:55544
2022-02-14 13:34:35 UTC: Upstream connection could not be established
2022-02-14 13:34:35 UTC: Upstream error for user 'xxx' to vhost 'xxx': #<AMQProxy::Upstream::Error:Cannot establish connection to upstream>
2022-02-14 13:34:35 UTC: Client disconnected: xxx:55544
```

Can you extend this log entry to be more verbose? Currently in debug mode it's saying nothing, and we don't know what is the reason. Our connections to rabbit instance are hanging randomly

**Comment by dentarg** [comment]
@alv91 can you try using `cloudamqp/amqproxy@sha256:eb72f8825fc76988d04c3fceefbea5b32790d34c31de92cf32df80e83d597524` from Docker Hub?

Also, if you can email CloudAMQP support, we could take a look at your specific cluster (feel free to refer to this issue)

**Comment by alv91** [comment]
Perfect! I see logs now :) Probably this is issue on our side. I need to confirm

**Comment by arealmaas** [comment]
Hi @alv91 , struggling with this ourselves. What was your issue specifically? 🙏

**Comment by alv91** [comment]
I dont know exactly, it was year ago. Logs should tell you more
