### ISSUE TITLE
Error target amqproxy failed to compile:

### ISSUE THREAD

**Issue by b3nelof0n** [cloudamqp/amqproxy#69]
i try to compile the source code buts not working with the current release

root@localhost:/tmp/amqproxy# shards build --release --production
Dependencies are satisfied
Building: amqproxy
Error target amqproxy failed to compile:
Showing last frame. Use --error-trace for full trace.

In src/amqproxy.cr:83:49

 83 | server.listen(@listen_address, @listen_port.to_i)
                                                  ^---
Error: undefined method 'to_i' for Nil (compile-time type is (Int32 | String | Nil))

Did you mean 'to_s'?

**Comment by carlhoerberg** [comment]
what version of crystal are you using? i can compile master just fine with crystal 1.4.1

**Comment by b3nelof0n** [comment]
root@localhost:~# crystal --version
Crystal 0.35.1 [5999ae29b] (2020-06-19)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu

root@localhost:~# uname -a
Linux localhost 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux

Debian Buster

**Comment by carlhoerberg** [comment]
Ok, that's an awful old version. Please install a more recent version of
the Crystal compiler

**Comment by carlhoerberg** [comment]
Or because you use such an old debian version i would recommend the static compiled crystal from here: https://packagecloud.io/84codes/crystal , works for all debian versions.
