### ISSUE TITLE
Improvement: Waiting until clients are closing connectins on SIGTERM

### ISSUE THREAD

**Issue by mruell** [cloudamqp/amqproxy#72]
Hi there!

We are planning to use the AMQProxy in our kubernetes cluster

One thing I stumbled accross is the following scenario:
Let's say there is a AMQProxy pod in every namespace. For compliance reasons its image is rebuilt weekly (and automatically deployed using a rolling restart)

Our worker pods send the SIGTERM to the PHP workers and they get 30 minutes to finish processing the AMQP messages and sending the ack.

Since the AMQProxy pod will also be redeployed it will also receive a sigterm and a new pod is started.

But the problem is that `AMQProxy` will kill the connections right away instead of waiting for all connections to be closed by the clients.

This means that the PHP workers will try to finish their message, and once they done try to send the ACK. But until then the connection from AMQProxy was already closed and the message requeued which leads to a message beeing processed multiple times.

Would it be possible that on SIGTERM AMQProxy only stops new connections and exits only if the last connection was closed?

Thanks and best,
Marvin

**Comment by dentarg** [comment]
> Would it be possible that on SIGTERM AMQProxy only stops new connections and exits only if the last connection was closed?

I think there needs to be a timeout too, but in general a feature like this ("drain") makes sense to me. Pull request appreciated :-)

**Comment by mruell** [comment]
Done :)
Hope you are able to review this soon!

**Comment by carlhoerberg** [comment]
Wrote #79 that achieves the same thing with less code

**Comment by mruell** [comment]
Awesome! Thanks again for the support here
