### ISSUE TITLE
Debian 11 (bullseye) support?

### ISSUE THREAD

**Issue by aghajani** [cloudamqp/amqproxy#73]
There is no release package for Debian 11 (bullseye). Any plans to add one?  
This will fail in debian 11:  
```shell
echo "deb https://packagecloud.io/cloudamqp/amqproxy/debian/ $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/amqproxy.list
apt update
```

**Comment by dentarg** [comment]
Now there's a package built for Debian 11, please try it out: https://packagecloud.io/app/cloudamqp/amqproxy/search?dist=debian%2Fbullseye
