### ISSUE TITLE
Not able to connect to rabbitmq server after upgrading to latest version. 

### ISSUE THREAD

**Issue by gdineshkumar627** [cloudamqp/amqproxy#81]
We are using amqps protocol for rabbitmq connection. It was working fine until v0.5.11. But after upgrading the docker image to the latest, I am getting SSL errors. 

`Upstream error for user '***' to vhost '***': #<AMQProxy::Upstream::Error:Cannot establish connection to upstream> (cause: #<OpenSSL::SSL::Error:SSL_connect: error:16000069:STORE routines::unregistered scheme>)`

**Comment by mruell** [comment]
I had the same issue when trying to build on ubuntu
The openssl version it was build with and it is running with is probably different

**Comment by carlhoerberg** [comment]
Fixed in master/latest
