### ISSUE TITLE
multiple rabbitmq servers

### ISSUE THREAD

**Issue by rbro** [cloudamqp/amqproxy#95]
In my application, I need to connect to multiple upstream rabbitmq servers.  I believe the way to do that now is to run multiple instances of amqproxy.  I'm not sure what would be involved, but would it be possible to allow multiple combinations of upstream servers and listen address/ports in a single config file?  Thanks for your help.

**Comment by carlhoerberg** [comment]
Its pretty easy and straightforward to run multiple instances of amqproxy in that case. Fail to see how the added complexity in amqproxy would outweight the potential benefit.

**Comment by rbro** [comment]
Yes, I agree that it's easy to run multiple instances of amqproxy.  I just wasn't sure if there were any advantages if multiple connections could be run in a single instance - less CPU or RAM, etc - similar to how nginx or proxysql allow multiple connections in a single instance.  If there aren't any advantages, I'm good with running multiple instances.  Thanks.

**Comment by carlhoerberg** [comment]
Not really, amqproxy is very lightweight in it self, not like a Java or Erlang VM. A single idle amqproxy uses like 3-5MB RAM and 0% CPU.
