### ISSUE TITLE
Configure max connections to upstream

### ISSUE THREAD

**Issue by jlindenbaum** [cloudamqp/amqproxy#97]
We run a PHP application that communicates to Rabbit through AMQProxy.

Recently we observed a failure mode we believe could be mitigated if AMQProxy allowed a configuration of the connection pool to fail incoming connections if the pool is at its maximum, and no existing connection can be reused. Effectively system protection.

This is similar behaviour we configure in ProxySQL to protect upstream databases from being overloaded.

Should an event occur where the system load increases such that our upstream Rabbit would be put in danger, we'd rather fail a small percentage of our incoming requests, rather than have the entire application degrade.

Going through the source in the pool class there does not appear to currently exist a flag to do this. I'd be happy to contribute this functionality, but I want to ensure this would be acceptable for the project.

**Comment by carlhoerberg** [comment]
Yes, it's something we would accept

**Comment by carlhoerberg** [comment]
With v2.0.0 we do channel pooling, and the number of upstream connections are vastly lower now (we use up to `channel_max` channels of each upstream connection).
