### ISSUE TITLE
Upstream connection timeout

### ISSUE THREAD

**Issue by milanzivanovic** [cloudamqp/amqproxy#98]
Hi there - is there any way to configure connection timeout on proxy side or to be respected by client's config?

Right now we are connecting to RabbitMQ cluster through amqproxy with connection timeout of 3sec.
If proxy isn't available, client throws `Connection timeout` error, but in case proxy is working but upstream (broker) isn't available, we experience ~5min wait before we get `Broken pipe or closed connection` error. Is that expected behaviour, and is there anything that could be set to proxy to interrupt the connection attempt if request takes for longer than 3 seconds to connect?

Thanks,
Milan.

**Comment by timothyclarke** [comment]
Hi @carlhoerberg I'm encountering this one too. Is this something you guys are aware of ?

**Comment by dentarg** [comment]
Makes sense to me. Contributions welcome.

**Comment by dentarg** [comment]
I think this issue is the same as https://github.com/cloudamqp/amqproxy/issues/118
