### ISSUE TITLE
Unknown DW_FORM_data16: Exception during execution

### ISSUE THREAD

**Issue by thannaske** [cloudamqp/amqproxy#99]
I'm running amqproxy in Docker and I'm getting exception during the execution. Unfortunately I'm not able to further debug that issue. The exceptions are occurring randomly after no fixed timeframe (can be minutes can be hours).

```
2023-01-09 16:29:48 UTC: Proxy upstream: 10.10.100.33:5672
2023-01-09 16:29:48 UTC: Proxy listening on 0.0.0.0:5673
Failed to raise an exception: END_OF_STACK
[0x42ede6] ???
[0x405958] ???
[0x4117e9] ???
[0x40c3e9] ???
[0x6ff330] ???
Tried to raise:: Unknown DW_FORM_data16 (Exception)
  from usr/share/crystal/src/crystal/dwarf/info.cr:83:29 in '??'
  from usr/share/crystal/src/crystal/dwarf/info.cr:67:23 in '??'
  from usr/share/crystal/src/exception/call_stack/elf.cr:10:7 in '??'
  from src/ldso/dl_iterate_phdr.c:45:1 in '??'
```

Version: amqproxy 0.6.1

**Comment by carlhoerberg** [comment]
A bug in old a Crystal version. Upgrade to a newer amqproxy which is compiled with a later Crystal version. https://github.com/crystal-lang/crystal/pull/12497

**Comment by thannaske** [comment]
Awesome thank you so much for your feedback.
